"""
deck.py
────────
Assembles ORBIC_Investor_Presentation.pptx — 12 slides, native editable
text/shapes/tables on a dark "energy command center" theme, with the
diagram PNGs from assets/ (generated by diagrams.py) embedded where useful.

Run:
    python diagrams.py   # generates assets/*.png (only needed once, or after edits)
    python deck.py        # builds ORBIC_Investor_Presentation.pptx

All factual claims are sourced from docs/AMERIPOWER_RISK_PORTFOLIO_MD.md,
docs/ENROLLMENT_RULES.md, docs/BILLING_ENGINE.md, and the application source
files listed in README.md. See README.md "Verified claims" table for the
file/line citation behind every Built/Operational/Roadmap label used here.
"""

import os

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import qn

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")
OUT = os.path.join(HERE, "ORBIC_Investor_Presentation.pptx")

# ── Palette (mirrors diagrams.py) ────────────────────────────────────────────
BG = RGBColor(0x08, 0x0C, 0x16)
PANEL = RGBColor(0x0F, 0x18, 0x28)
PANEL_LIGHT = RGBColor(0x15, 0x21, 0x36)
BORDER = RGBColor(0x24, 0x34, 0x4E)
CYAN = RGBColor(0x22, 0xD3, 0xEE)
BLUE = RGBColor(0x42, 0x85, 0xF4)
AMBER = RGBColor(0xF5, 0xA6, 0x23)
WHITE = RGBColor(0xE8, 0xEE, 0xF7)
MUTED = RGBColor(0x8C, 0xA0, 0xBC)
MUTED2 = RGBColor(0x5F, 0x70, 0x8A)
GREEN = RGBColor(0x34, 0xD3, 0x99)
YELLOW = RGBColor(0xFB, 0xBF, 0x24)
RED = RGBColor(0xF8, 0x71, 0x71)

FONT = "Segoe UI"
FONT_SEMI = "Segoe UI Semibold"

SW, SH = Inches(13.333), Inches(7.5)

prs = Presentation()
prs.slide_width = SW
prs.slide_height = SH
BLANK = prs.slide_layouts[6]


# ── Low-level helpers ─────────────────────────────────────────────────────
def add_slide():
    slide = prs.slides.add_slide(BLANK)
    bg = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SW, SH)
    bg.fill.solid()
    bg.fill.fore_color.rgb = BG
    bg.line.fill.background()
    bg.shadow.inherit = False
    # send to back
    sp = bg._element
    sp.getparent().remove(sp)
    slide.shapes._spTree.insert(2, sp)
    return slide


def set_notes(slide, text):
    slide.notes_slide.notes_text_frame.text = text


def textbox(slide, x, y, w, h, text, size=18, color=WHITE, bold=False, align=PP_ALIGN.LEFT,
            font=FONT, anchor=MSO_ANCHOR.TOP, line_spacing=1.0, italic=False):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    tf.margin_left = 0
    tf.margin_right = 0
    tf.margin_top = 0
    tf.margin_bottom = 0
    lines = text.split("\n")
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = line_spacing
        r = p.add_run()
        r.text = line
        r.font.size = Pt(size)
        r.font.bold = bold
        r.font.italic = italic
        r.font.name = font
        r.font.color.rgb = color
    return tb


def rect(slide, x, y, w, h, fill=None, line_color=None, line_w=1.0, radius=None, shadow=False):
    shape_type = MSO_SHAPE.ROUNDED_RECTANGLE if radius else MSO_SHAPE.RECTANGLE
    sh = slide.shapes.add_shape(shape_type, x, y, w, h)
    if radius:
        try:
            sh.adjustments[0] = radius
        except Exception:
            pass
    if fill is None:
        sh.fill.background()
    else:
        sh.fill.solid()
        sh.fill.fore_color.rgb = fill
    if line_color is None:
        sh.line.fill.background()
    else:
        sh.line.color.rgb = line_color
        sh.line.width = Pt(line_w)
    sh.shadow.inherit = False
    return sh


def picture_cover(slide, path, x, y, w, h):
    return slide.shapes.add_picture(path, x, y, width=w, height=h)


def kicker(slide, text, x=Inches(0.7), y=Inches(0.42), color=CYAN):
    textbox(slide, x, y, Inches(8), Inches(0.35), text.upper(), size=13, color=color,
            bold=True, font=FONT_SEMI)


def title(slide, text, x=Inches(0.7), y=Inches(0.72), size=30, w=Inches(11.9)):
    textbox(slide, x, y, w, Inches(0.9), text, size=size, color=WHITE, bold=True)


def slide_number(slide, n):
    textbox(slide, Inches(12.55), Inches(7.12), Inches(0.6), Inches(0.3), f"{n:02d} / 12",
            size=10, color=MUTED2, align=PP_ALIGN.RIGHT)
    textbox(slide, Inches(0.7), Inches(7.12), Inches(2.5), Inches(0.3), "ORBIC",
            size=10, color=MUTED2, bold=True, font=FONT_SEMI)


def status_pill(slide, x, y, label, status="built", w=Inches(1.5), h=Inches(0.34)):
    color = {"built": GREEN, "operational": GREEN, "partial": AMBER, "roadmap": MUTED2}[status]
    text = {"built": "BUILT", "operational": "OPERATIONAL", "partial": "PARTIALLY BUILT",
            "roadmap": "ROADMAP"}[status]
    sh = rect(slide, x, y, w, h, fill=None, line_color=color, line_w=1.25, radius=0.5)
    tf = sh.text_frame
    tf.margin_left = 0
    tf.margin_right = 0
    tf.word_wrap = False
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.CENTER
    r = p.add_run()
    r.text = text
    r.font.size = Pt(10.5)
    r.font.bold = True
    r.font.name = FONT_SEMI
    r.font.color.rgb = color
    if label:
        textbox(slide, x + w + Inches(0.12), y - Inches(0.02), Inches(3.5), h, label,
                size=12, color=WHITE)
    return sh


def module_card(slide, x, y, w, h, title_txt, desc, status, accent=CYAN):
    rect(slide, x, y, w, h, fill=PANEL, line_color=BORDER, line_w=1, radius=0.06)
    rect(slide, x, y, w, Emu(38100), fill=accent)  # top accent strip (~0.03in)
    textbox(slide, x + Inches(0.22), y + Inches(0.16), w - Inches(0.44), Inches(0.4),
            title_txt, size=15, color=WHITE, bold=True, font=FONT_SEMI)
    textbox(slide, x + Inches(0.22), y + Inches(0.58), w - Inches(0.44), h - Inches(0.9),
            desc, size=11, color=MUTED, line_spacing=1.15)
    status_pill(slide, x + Inches(0.22), y + h - Inches(0.48), "", status,
                w=Inches(1.35), h=Inches(0.3))


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 1 — Cover
# ═══════════════════════════════════════════════════════════════════════════
def slide_01():
    s = add_slide()
    hero = os.path.join(ASSETS, "hero_graphic.png")
    picture_cover(s, hero, 0, 0, SW, SH)

    textbox(s, Inches(0.85), Inches(0.75), Inches(4), Inches(0.4), "ENERGY INTELLIGENCE ENGINE",
            size=13, color=CYAN, bold=True, font=FONT_SEMI)

    textbox(s, Inches(0.8), Inches(2.55), Inches(9.5), Inches(1.3), "ORBIC", size=88,
            color=WHITE, bold=True)
    textbox(s, Inches(0.85), Inches(3.85), Inches(9.8), Inches(1.1),
            "The Energy Intelligence Engine for\nRetail Energy Providers",
            size=26, color=CYAN, bold=False, line_spacing=1.1)

    textbox(s, Inches(0.85), Inches(5.35), Inches(8.5), Inches(0.5),
            "Contract to settlement — one connected platform for ERCOT retail electric providers.",
            size=14, color=MUTED)

    textbox(s, Inches(0.85), Inches(6.85), Inches(6), Inches(0.4),
            "Investor Briefing  ·  Confidential", size=11, color=MUTED2)

    set_notes(s, "ORBIC is a purpose-built energy intelligence engine for retail energy "
                  "providers (REPs) operating in ERCOT — not a generic SaaS tool retrofitted "
                  "for energy. Investor takeaway: this is a single connected platform spanning "
                  "the entire retail energy lifecycle, from the moment a contract is confirmed "
                  "through settlement and risk monitoring, with an AI layer operating on top of "
                  "live data rather than bolted on as a chatbot.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 2 — The problem
# ═══════════════════════════════════════════════════════════════════════════
def slide_02():
    s = add_slide()
    kicker(s, "The Problem")
    title(s, "Retail energy providers run on disconnected systems")

    textbox(s, Inches(0.7), Inches(1.55), Inches(11.5), Inches(0.6),
            "A typical ERCOT REP stitches together a CRM, a billing vendor, spreadsheets for "
            "hedging, and a separate BI tool — none of which share a data model.",
            size=15, color=MUTED, line_spacing=1.2)

    pains = [
        ("Fragmented lifecycle", "Enrollment, billing, and collections live in different "
         "systems with no single source of truth for a customer's contract history."),
        ("Manual portfolio risk", "Open position, hedge coverage, and mark-to-market are "
         "tracked in spreadsheets, refreshed periodically instead of continuously."),
        ("Forecasting blind spots", "Load forecasts are built once and rarely reconciled "
         "against what ERCOT actually settles — errors compound silently."),
        ("Operational data buried", "Staff spend hours per day searching multiple screens "
         "just to answer routine questions about a customer or an account."),
    ]
    x0, y0, w, h, gap = Inches(0.7), Inches(2.55), Inches(5.6), Inches(2.0), Inches(0.3)
    for i, (t, d) in enumerate(pains):
        col, row = i % 2, i // 2
        x = x0 + col * (w + gap)
        y = y0 + row * (h + gap)
        rect(s, x, y, w, h, fill=PANEL, line_color=BORDER, line_w=1, radius=0.06)
        rect(s, x, y, Emu(45720), h, fill=RED)
        textbox(s, x + Inches(0.3), y + Inches(0.22), w - Inches(0.6), Inches(0.4), t,
                size=16, color=WHITE, bold=True, font=FONT_SEMI)
        textbox(s, x + Inches(0.3), y + Inches(0.68), w - Inches(0.6), h - Inches(0.9), d,
                size=12.5, color=MUTED, line_spacing=1.25)

    slide_number(s, 2)
    set_notes(s, "Investor takeaway: the pain isn't a missing feature — it's structural "
                  "fragmentation. Every REP either buys 4-5 point solutions and integrates them "
                  "poorly, or accepts blind spots in risk and forecasting. That fragmentation is "
                  "the wedge ORBIC is built to close.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 3 — The solution (lifecycle ring)
# ═══════════════════════════════════════════════════════════════════════════
def slide_03():
    s = add_slide()
    kicker(s, "The Solution")
    title(s, "One connected platform for the full retail energy lifecycle")

    img = os.path.join(ASSETS, "lifecycle_ring.png")
    picture_cover(s, img, Inches(2.55), Inches(1.35), Inches(8.2), Inches(6.15))

    slide_number(s, 3)
    set_notes(s, "ORBIC models the retail energy business as one continuous lifecycle rather "
                  "than a set of separate modules: contract confirmation flows into enrollment "
                  "and MasterRoll generation, into activation, into billing and collections, and "
                  "in parallel drives portfolio forecasting, hedging, settlement, and risk "
                  "monitoring — with an AI layer that can answer questions across all of it. "
                  "Investor takeaway: the value isn't any single module, it's that they all read "
                  "and write the same underlying data.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 4 — Why ORBIC is different
# ═══════════════════════════════════════════════════════════════════════════
def slide_04():
    s = add_slide()
    kicker(s, "Why ORBIC Is Different")
    title(s, "Not a CRM. Not a billing tool. Not a chatbot bolted onto a dashboard.")

    rows = [
        ("A generic CRM", "Tracks contacts and deals — has no concept of ERCOT contract "
         "types, MasterRoll generation, or TDSP switch rules."),
        ("A billing platform", "Processes charges — has no visibility into open position, "
         "hedge coverage, or forecast risk driving those charges."),
        ("A BI dashboard", "Visualizes historical data — has no forecasting engine, no "
         "self-healing checkpoints, and can't take action."),
        ("A standalone AI chatbot", "Answers from a static knowledge base or general "
         "training data — has no live connection to a REP's actual accounts, pricing, or "
         "positions."),
    ]
    y = Inches(1.7)
    rh = Inches(1.15)
    for i, (bad, why) in enumerate(rows):
        yy = y + i * (rh + Inches(0.08))
        rect(s, Inches(0.7), yy, Inches(11.9), rh, fill=PANEL, line_color=BORDER, line_w=1, radius=0.05)
        textbox(s, Inches(1.0), yy + Inches(0.18), Inches(3.3), Inches(0.8), bad,
                size=16, color=RED, bold=True, font=FONT_SEMI, anchor=MSO_ANCHOR.MIDDLE)
        textbox(s, Inches(4.5), yy + Inches(0.15), Inches(7.7), Inches(0.85), why,
                size=12.5, color=MUTED, line_spacing=1.2, anchor=MSO_ANCHOR.MIDDLE)

    textbox(s, Inches(0.7), Inches(6.55), Inches(11.9), Inches(0.5),
            "ORBIC is the operational system of record — the AI agent and every module act on "
            "the same live contracts, positions, and prices.", size=14, color=CYAN, bold=True)

    slide_number(s, 4)
    set_notes(s, "Investor takeaway: ORBIC's differentiation isn't a feature list — it's that "
                  "one connected data model underlies enrollment, billing, portfolio, risk, and "
                  "the AI agent. Competitors are point solutions; ORBIC is the system of record "
                  "those point solutions would otherwise need to integrate with.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 5 — Architecture
# ═══════════════════════════════════════════════════════════════════════════
def slide_05():
    s = add_slide()
    kicker(s, "Application Architecture")
    title(s, "A modern, tenant-isolated technology stack")

    img = os.path.join(ASSETS, "architecture_diagram.png")
    picture_cover(s, img, Inches(0.55), Inches(1.35), Inches(9.6), Inches(6.0))

    stats = [
        ("109", "Frontend pages"),
        ("45", "API routers"),
        ("39", "Controllers"),
        ("38", "DB migrations"),
    ]
    x0, y0 = Inches(10.35), Inches(1.55)
    for i, (n, l) in enumerate(stats):
        y = y0 + i * Inches(1.35)
        rect(s, x0, y, Inches(2.35), Inches(1.15), fill=PANEL, line_color=BORDER, line_w=1, radius=0.08)
        textbox(s, x0, y + Inches(0.1), Inches(2.35), Inches(0.6), n, size=30, color=CYAN,
                bold=True, align=PP_ALIGN.CENTER)
        textbox(s, x0, y + Inches(0.75), Inches(2.35), Inches(0.35), l, size=11, color=MUTED,
                align=PP_ALIGN.CENTER)

    slide_number(s, 5)
    set_notes(s, "Investor takeaway: this is a real, sizable codebase — 45 API routers and 109 "
                  "frontend pages — not a prototype. Each REP tenant runs its own isolated "
                  "database and app instance (confirmed via TenantMiddleware and the tenant "
                  "provisioning script), which is a meaningful data-isolation and compliance "
                  "story for enterprise energy customers.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 6 — Customer & contract lifecycle
# ═══════════════════════════════════════════════════════════════════════════
def slide_06():
    s = add_slide()
    kicker(s, "Customer & Contract Lifecycle")
    title(s, "From confirmation to collections — one auditable chain")

    img = os.path.join(ASSETS, "contract_lifecycle.png")
    picture_cover(s, img, Inches(0.4), Inches(1.35), Inches(12.5), Inches(5.15))

    status_pill(s, Inches(0.7), Inches(6.65), "Enrollment Engine, MasterRoll, Activation, Billing pipeline", "built", w=Inches(1.35))
    status_pill(s, Inches(6.9), Inches(6.65), "Enrollment-time county/exemption capture", "roadmap", w=Inches(1.35))

    slide_number(s, 6)
    set_notes(s, "Investor takeaway: the enrollment engine supports six real ERCOT contract "
                  "types (New, Renewal, Assignment, B&E, Addition, Multi-Start) with active-"
                  "contract guard rules, generates a 128-column MasterRoll file, and activation "
                  "writes directly into contract_renewal — the single source of truth. The "
                  "billing engine's EDI 867/810 ingestion, tax computation, and invoice "
                  "generation are built and verified against real data. One open item: county/"
                  "exemption capture at enrollment time is not yet built.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 7 — Portfolio & risk intelligence
# ═══════════════════════════════════════════════════════════════════════════
def slide_07():
    s = add_slide()
    kicker(s, "Portfolio & Risk Intelligence")
    title(s, "A daily, weighted view of portfolio risk")

    img = os.path.join(ASSETS, "risk_composite.png")
    picture_cover(s, img, Inches(0.6), Inches(1.3), Inches(5.6), Inches(5.6))

    cards = [
        ("Position Risk — 40%", "Forecast load vs. hedged supply, evaluated across four "
         "time horizons.", "built"),
        ("Price Risk — 25%", "Mark-to-market P&L computed from the hedge book against "
         "market prices.", "built"),
        ("Customer Risk — 20%", "Collections delinquency exposure across the active "
         "customer base.", "built"),
        ("Weather Risk — 15%", "Near-term load forecast compared against prior-year "
         "actuals.", "built"),
    ]
    x0, y0, w, h = Inches(6.5), Inches(1.35), Inches(6.15), Inches(1.28)
    for i, (t, d, status) in enumerate(cards):
        y = y0 + i * (h + Inches(0.1))
        module_card(s, x0, y, w, h, t, d, status)

    slide_number(s, 7)
    set_notes(s, "Investor takeaway: this Risk Assessment Dashboard is one of the most recently "
                  "shipped features (verified via git history) — a real 4-factor weighted "
                  "engine, not a mockup. Position, price, customer, and weather risk are each "
                  "computed from live tables (hedge_book, mtm_results, collections, load "
                  "forecasts) and rolled into one daily GREEN/YELLOW/RED score persisted to "
                  "risk_scores. This turns portfolio risk from a periodic spreadsheet exercise "
                  "into a live, always-current signal.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 8 — AI operating layer
# ═══════════════════════════════════════════════════════════════════════════
def slide_08():
    s = add_slide()
    kicker(s, "AI Operating Layer")
    title(s, "Orbi: an agent grounded in live operational data")

    img = os.path.join(ASSETS, "ai_agent_diagram.png")
    picture_cover(s, img, Inches(0.5), Inches(1.35), Inches(12.3), Inches(5.15))

    status_pill(s, Inches(0.7), Inches(6.65), "12 live tool-calling functions against production FastAPI endpoints", "built", w=Inches(1.35))

    slide_number(s, 8)
    set_notes(s, "Investor takeaway: Orbi is not a chatbot with a system prompt and hope — it's "
                  "a tool-calling agent (OpenAI GPT-4o-mini) with 12 real functions "
                  "(search_customers, get_open_position, get_ercot_forecast, get_past_due_"
                  "accounts, and more) that call the exact same FastAPI endpoints the UI uses. "
                  "Its system prompt explicitly instructs it to never invent data and always "
                  "call a tool. This is what makes it an operating layer on top of ORBIC's data, "
                  "not a separate product.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 9 — Forecasting & monitoring advantage
# ═══════════════════════════════════════════════════════════════════════════
def slide_09():
    s = add_slide()
    kicker(s, "Forecasting & Monitoring Advantage")
    title(s, "A layered forecast engine that checks its own work")

    img = os.path.join(ASSETS, "forecast_layers.png")
    picture_cover(s, img, Inches(2.15), Inches(1.25), Inches(9.0), Inches(6.2))

    slide_number(s, 9)
    set_notes(s, "Investor takeaway: three of four forecast layers are built and live — "
                  "including Layer 4, the 7-day ERCOT LFC override, which is wired directly "
                  "into the production forecast path used by the Position Screen today. Layer 3 "
                  "(NOAA seasonal El Niño/La Niña adjustment) is explicitly roadmap, not yet "
                  "built — we are not claiming it as complete. On top of the forecast itself, "
                  "four nightly self-healing checkpoints (7-Day Mirror Test, Historical "
                  "Backtest, Energy Balance Sanity, Portfolio Ratio Check) continuously grade "
                  "forecast quality and persist results — this automatic quality control is a "
                  "meaningful differentiator most REP forecasting tools don't have.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 10 — Product maturity matrix
# ═══════════════════════════════════════════════════════════════════════════
def slide_10():
    s = add_slide()
    kicker(s, "Current Product Maturity")
    title(s, "What's built, what's operational, what's next")

    rows = [
        ("Enrollment Engine & MasterRoll", "built"),
        ("Billing Engine (EDI ingestion → tax → invoice)", "built"),
        ("Contract Activation & Guard Rules", "built"),
        ("Portfolio / Hedging / DAM Purchases", "built"),
        ("Manual Mark-to-Market (MTM)", "built"),
        ("Risk Assessment Dashboard (4-factor)", "built"),
        ("Forecast Layers 1, 2 & 4 (DNA, Growth, LFC Override)", "built"),
        ("Self-Healing Monitoring (4 nightly checkpoints)", "built"),
        ("Orbi AI Agent (12 live tools)", "built"),
        ("Enrollment-time county / exemption capture", "roadmap"),
        ("Forecast Layer 3 — NOAA seasonal adjustment", "roadmap"),
        ("Live MTM market-price feeds (CME / ICE / Bloomberg)", "roadmap"),
        ("Settlement reconciliation (3-way match)", "roadmap"),
    ]

    x0, y0 = Inches(0.7), Inches(1.55)
    col_w, row_h = Inches(7.6), Inches(0.4)
    for i, (label, status) in enumerate(rows):
        y = y0 + i * row_h
        if i % 2 == 0:
            rect(s, x0, y, Inches(11.9), row_h, fill=PANEL, line_color=None)
        textbox(s, x0 + Inches(0.15), y + Inches(0.04), col_w, row_h, label, size=13,
                color=WHITE, anchor=MSO_ANCHOR.MIDDLE)
        status_pill(s, x0 + Inches(9.6), y + Inches(0.03), "", status, w=Inches(1.55), h=Inches(0.32))

    slide_number(s, 10)
    set_notes(s, "Investor takeaway: this is a candid maturity snapshot, not a sales sheet — "
                  "nine capabilities are built and operational today across enrollment, billing, "
                  "portfolio, risk, forecasting, monitoring, and AI. Four specific items are "
                  "explicitly labeled roadmap and are not claimed as complete: county/exemption "
                  "capture at enrollment, NOAA seasonal forecast adjustment (Layer 3), live MTM "
                  "market-price feeds, and full settlement reconciliation.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 11 — Target customers & business model
# ═══════════════════════════════════════════════════════════════════════════
def slide_11():
    s = add_slide()
    kicker(s, "Target Customers & Business Model")
    title(s, "Built for licensed retail electric providers in ERCOT")

    left_items = [
        "Licensed Retail Electric Providers (REPs) operating in the ERCOT market",
        "REPs currently running enrollment, billing, and portfolio tracking across "
        "disconnected point solutions and spreadsheets",
        "Growing REPs that need portfolio and risk visibility without building an "
        "in-house engineering team",
    ]
    rect(s, Inches(0.7), Inches(1.6), Inches(5.9), Inches(4.9), fill=PANEL, line_color=BORDER, line_w=1, radius=0.05)
    textbox(s, Inches(1.0), Inches(1.85), Inches(5.3), Inches(0.4), "Who ORBIC serves",
            size=16, color=CYAN, bold=True, font=FONT_SEMI)
    y = Inches(2.4)
    for item in left_items:
        rect(s, Inches(1.0), y + Inches(0.08), Inches(0.08), Inches(0.08), fill=CYAN)
        textbox(s, Inches(1.25), y, Inches(5.05), Inches(1.0), item, size=12.5, color=MUTED,
                line_spacing=1.25)
        y += Inches(1.15)

    right_items = [
        "Multi-tenant architecture: one isolated database and app instance per REP "
        "tenant, provisioned via a repeatable onboarding script",
        "Platform model: the same enrollment, billing, portfolio, and AI modules "
        "serve every tenant, with tenant-specific data fully isolated",
        "Deployment is verified and repeatable (provision_tenant.py), which is the "
        "operational foundation for onboarding additional REPs",
    ]
    rect(s, Inches(6.75), Inches(1.6), Inches(5.9), Inches(4.9), fill=PANEL, line_color=BORDER, line_w=1, radius=0.05)
    textbox(s, Inches(7.05), Inches(1.85), Inches(5.3), Inches(0.4), "How ORBIC is delivered",
            size=16, color=AMBER, bold=True, font=FONT_SEMI)
    y = Inches(2.4)
    for item in right_items:
        rect(s, Inches(7.05), y + Inches(0.08), Inches(0.08), Inches(0.08), fill=AMBER)
        textbox(s, Inches(7.3), y, Inches(5.15), Inches(1.1), item, size=12.5, color=MUTED,
                line_spacing=1.25)
        y += Inches(1.3)

    slide_number(s, 11)
    set_notes(s, "Investor takeaway: we are deliberately not citing market-size, revenue, or "
                  "customer-count figures here — none are verified yet. What is verified is the "
                  "architecture: a real, scripted, DB-per-tenant provisioning path "
                  "(api/scripts/provision_tenant.py) that is the operational basis for a "
                  "multi-tenant SaaS business model serving licensed ERCOT REPs.")


# ═══════════════════════════════════════════════════════════════════════════
# SLIDE 12 — Vision & investment opportunity
# ═══════════════════════════════════════════════════════════════════════════
def slide_12():
    s = add_slide()
    hero = os.path.join(ASSETS, "hero_graphic.png")
    picture_cover(s, hero, 0, 0, SW, SH)

    kicker(s, "Long-Term Vision", y=Inches(0.9))
    textbox(s, Inches(0.7), Inches(1.35), Inches(10.5), Inches(1.3),
            "The energy intelligence engine\nfor every retail energy provider",
            size=38, color=WHITE, bold=True, line_spacing=1.05)

    pillars = [
        ("Complete the forecast stack", "Ship Layer 3 seasonal adjustment and live MTM "
         "market-price feeds to close the remaining roadmap items."),
        ("Deepen the risk & settlement layer", "Extend risk monitoring toward full "
         "settlement reconciliation and richer historical analysis."),
        ("Scale the AI operating layer", "Grow Orbi's tool coverage as new modules ship, "
         "keeping every answer grounded in live tenant data."),
        ("Onboard additional REP tenants", "Use the existing provisioning path to bring "
         "on new licensed ERCOT retail providers."),
    ]
    x0, y0, w, h, gap = Inches(0.7), Inches(3.1), Inches(5.7), Inches(1.75), Inches(0.25)
    for i, (t, d) in enumerate(pillars):
        col, row = i % 2, i // 2
        x = x0 + col * (w + gap)
        y = y0 + row * (h + gap)
        rect(s, x, y, w, h, fill=PANEL, line_color=CYAN, line_w=1, radius=0.06)
        textbox(s, x + Inches(0.25), y + Inches(0.18), w - Inches(0.5), Inches(0.4), t,
                size=15, color=CYAN, bold=True, font=FONT_SEMI)
        textbox(s, x + Inches(0.25), y + Inches(0.62), w - Inches(0.5), h - Inches(0.85), d,
                size=12, color=MUTED, line_spacing=1.2)

    slide_number(s, 12)
    set_notes(s, "Investor takeaway: the vision is a natural extension of what's already built "
                  "— completing the forecast and settlement stack, scaling the AI layer as new "
                  "modules ship, and onboarding additional REP tenants onto the existing "
                  "multi-tenant provisioning path. No revenue, market-size, or customer "
                  "projections are asserted here, consistent with using only verified claims "
                  "throughout this deck; those figures belong in a dedicated financial model "
                  "reviewed separately with the team.")


def main():
    slide_01()
    slide_02()
    slide_03()
    slide_04()
    slide_05()
    slide_06()
    slide_07()
    slide_08()
    slide_09()
    slide_10()
    slide_11()
    slide_12()
    prs.save(OUT)
    print("Saved", OUT)


if __name__ == "__main__":
    main()
