"""
deck.py
────────
Assembles ORBIC_Investor_Presentation.pptx from scratch using python-pptx.
Native, fully editable text/shapes/tables — no embedded slide images except
the diagram PNGs generated by diagrams.py. Run after editing copy/layout:

    python deck.py

Every capability claim on every slide is labeled BUILT / OPERATIONAL /
PARTIALLY BUILT / IN PROGRESS / ROADMAP against a verified source — see
README.md "Verified claims" table. No customers, revenue, market size,
savings, accuracy percentages, or partnerships are claimed anywhere.
"""

import os

from PIL import Image
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

HERE = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(HERE, "assets")
OUT = os.path.join(HERE, "ORBIC_Investor_Presentation.pptx")

TOTAL_SLIDES = 22


def C(hexint):
    return RGBColor((hexint >> 16) & 255, (hexint >> 8) & 255, hexint & 255)


BG = 0x080C16
PANEL = 0x0F1828
PANEL_LIGHT = 0x152136
BORDER = 0x24344E
CYAN = 0x22D3EE
BLUE = 0x4285F4
AMBER = 0xF5A623
WHITE = 0xE8EEF7
MUTED = 0x8CA0BC
MUTED2 = 0x5F708A
GREEN = 0x34D399
YELLOW = 0xFBBF24
RED = 0xF87171
PURPLE = 0xC484E0

FONT = "Segoe UI"
FONT_SEMI = "Segoe UI Semibold"

SW, SH = Inches(13.333), Inches(7.5)

prs = Presentation()
prs.slide_width = SW
prs.slide_height = SH
BLANK = prs.slide_layouts[6]

STATUS = {
    "built": (GREEN, "BUILT"),
    "operational": (GREEN, "OPERATIONAL"),
    "partial": (AMBER, "PARTIALLY BUILT"),
    "progress": (AMBER, "IN PROGRESS"),
    "roadmap": (MUTED2, "ROADMAP"),
}


# ── Core helpers ─────────────────────────────────────────────────────────────
def add_slide():
    slide = prs.slides.add_slide(BLANK)
    sp = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, SW, SH)
    sp.fill.solid()
    sp.fill.fore_color.rgb = C(BG)
    sp.line.fill.background()
    sp.shadow.inherit = False
    slide.shapes._spTree.remove(sp._element)
    slide.shapes._spTree.insert(2, sp._element)
    return slide


def set_notes(slide, text):
    slide.notes_slide.notes_text_frame.text = text


def textbox(slide, x, y, w, h, text, size=18, color=WHITE, bold=False,
            align=PP_ALIGN.LEFT, font=FONT, anchor=MSO_ANCHOR.TOP,
            line_spacing=1.0, italic=False):
    tb = slide.shapes.add_textbox(x, y, w, h)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.vertical_anchor = anchor
    tf.margin_left = tf.margin_right = tf.margin_top = tf.margin_bottom = 0
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        p.line_spacing = line_spacing
        r = p.add_run()
        r.text = ln
        r.font.size = Pt(size)
        r.font.bold = bold
        r.font.italic = italic
        r.font.name = font
        r.font.color.rgb = C(color)
    return tb


def rect(slide, x, y, w, h, fill=None, line_color=None, line_w=1.0, radius=None, shadow=False):
    shape_type = MSO_SHAPE.ROUNDED_RECTANGLE if radius is not None else MSO_SHAPE.RECTANGLE
    sp = slide.shapes.add_shape(shape_type, x, y, w, h)
    if radius is not None:
        try:
            sp.adjustments[0] = radius
        except Exception:
            pass
    if fill is not None:
        sp.fill.solid()
        sp.fill.fore_color.rgb = C(fill)
    else:
        sp.fill.background()
    if line_color is not None:
        sp.line.color.rgb = C(line_color)
        sp.line.width = Pt(line_w)
    else:
        sp.line.fill.background()
    sp.shadow.inherit = shadow
    return sp


def picture_fit(slide, path, x, y, max_w, max_h, align="center"):
    im = Image.open(path)
    iw, ih = im.size
    scale = min(max_w / iw, max_h / ih)
    w = int(iw * scale)
    h = int(ih * scale)
    px = x + (max_w - w) // 2 if align == "center" else x
    py = y + (max_h - h) // 2
    return slide.shapes.add_picture(path, px, py, width=Emu(int(w)), height=Emu(int(h)))


def kicker(slide, text, x=Inches(0.7), y=Inches(0.42), color=CYAN):
    textbox(slide, x, y, Inches(10), Inches(0.35), text.upper(), size=13, color=color,
            bold=True, font=FONT_SEMI)


def title(slide, text, x=Inches(0.7), y=Inches(0.72), size=30, w=Inches(11.9), h=Inches(0.9)):
    textbox(slide, x, y, w, h, text, size=size, color=WHITE, bold=True, font=FONT_SEMI)


def slide_number(slide, n):
    textbox(slide, Inches(12.15), Inches(7.12), Inches(1.0), Inches(0.3),
            f"{n:02d} / {TOTAL_SLIDES}", size=10, color=MUTED2, align=PP_ALIGN.RIGHT)
    textbox(slide, Inches(0.7), Inches(7.12), Inches(3.0), Inches(0.3),
            "ORBIC", size=10, color=MUTED2, bold=True, font=FONT_SEMI)


def status_pill(slide, x, y, status, w=Inches(1.85), h=Inches(0.34)):
    color, label = STATUS[status]
    rect(slide, x, y, w, h, fill=None, line_color=color, line_w=1.25, radius=0.5)
    textbox(slide, x, y, w, h, label, size=10.5, color=color, bold=True, font=FONT_SEMI,
            align=PP_ALIGN.CENTER, anchor=MSO_ANCHOR.MIDDLE)


def module_card(slide, x, y, w, h, title_txt, desc, status, accent=CYAN):
    rect(slide, x, y, w, h, fill=PANEL, line_color=BORDER, line_w=1.0, radius=0.06)
    rect(slide, x, y, Inches(0.06), h, fill=accent)
    textbox(slide, x + Inches(0.22), y + Inches(0.16), w - Inches(0.44), Inches(0.4),
            title_txt, size=15, color=WHITE, bold=True, font=FONT_SEMI)
    textbox(slide, x + Inches(0.22), y + Inches(0.58), w - Inches(0.44), h - Inches(1.0),
            desc, size=11.5, color=MUTED, line_spacing=1.12)
    pw = Inches(1.7)
    status_pill(slide, x + w - pw - Inches(0.2), y + h - Inches(0.5), status, w=pw, h=Inches(0.32))


def bullet_list(slide, x, y, w, items, size=14, gap=Inches(0.36), color=WHITE, marker_color=CYAN):
    cy = y
    for it in items:
        rect(slide, x, cy + Inches(0.09), Inches(0.09), Inches(0.09), fill=marker_color, radius=0.5)
        textbox(slide, x + Inches(0.28), cy, w - Inches(0.28), gap, it, size=size, color=color,
                line_spacing=1.08)
        cy += gap
    return cy


# ── Slide 1 — Cover ──────────────────────────────────────────────────────────
def slide_01():
    s = add_slide()
    picture_fit(s, os.path.join(ASSETS, "hero_graphic.png"), 0, 0, SW, SH)
    kicker(s, "Investor Overview", y=Inches(2.15))
    textbox(s, Inches(0.7), Inches(2.55), Inches(9), Inches(1.6), "ORBIC",
            size=74, color=WHITE, bold=True, font=FONT_SEMI)
    textbox(s, Inches(0.7), Inches(3.95), Inches(8.6), Inches(0.9),
            "The Intelligent Operating System for Retail Energy Providers",
            size=22, color=CYAN, font=FONT)
    textbox(s, Inches(0.7), Inches(4.65), Inches(8.6), Inches(0.5),
            "Sales  ·  Operations  ·  Portfolio  ·  Collections — one connected platform",
            size=14, color=MUTED)
    slide_number(s, 1)
    set_notes(s, "ORBIC is not a point tool for one part of the REP business — it is being built as the "
                 "operating system that runs the whole retail energy provider: sales, enrollment, billing, "
                 "portfolio/risk, settlements, and collections, on one data model. This deck walks through "
                 "the four operating engines, the lifecycle that connects them, and an honest, source-verified "
                 "picture of what is built today versus what is on the roadmap.")


# ── Slide 2 — The REP operating problem ─────────────────────────────────────
def slide_02():
    s = add_slide()
    kicker(s, "The Problem")
    title(s, "Retail energy providers run on disconnected systems")
    frags = ["Sales / Pricing", "Enrollment", "Billing", "Portfolio / Hedging",
             "Settlements", "Collections", "Reporting"]
    fw = Inches(1.62)
    gap = Inches(0.14)
    total_w = fw * len(frags) + gap * (len(frags) - 1)
    fx = (SW - total_w) // 2
    fy = Inches(1.95)
    for i, name in enumerate(frags):
        x = fx + i * (fw + gap)
        rect(s, x, fy, fw, Inches(1.1), fill=PANEL, line_color=RED, line_w=1.0, radius=0.1)
        textbox(s, x + Inches(0.08), fy, fw - Inches(0.16), Inches(1.1), name, size=12.5,
                color=WHITE, bold=True, align=PP_ALIGN.CENTER, anchor=MSO_ANCHOR.MIDDLE,
                line_spacing=1.1)
    textbox(s, fx, fy + Inches(1.25), total_w, Inches(0.4),
            "Different tools. Different spreadsheets. No shared source of truth.",
            size=13, color=RED, italic=True, align=PP_ALIGN.CENTER)

    body_y = Inches(3.9)
    textbox(s, Inches(0.7), body_y, Inches(11.9), Inches(0.4),
            "When these functions don't talk to each other, every handoff is a place errors get in:",
            size=15, color=WHITE, bold=True)
    items = [
        "Margin loss — pricing and hedging decisions made without a live view of enrolled load or settlement risk",
        "Compliance exposure — PUC deadlines, tax rules, and audit trails tracked manually across disconnected files",
        "Customer-facing errors — enrollment delays, billing mistakes, and meter mix-ups that reach the customer",
        "Operational cost — headcount spent reconciling spreadsheets instead of running the business",
    ]
    bullet_list(s, Inches(0.9), body_y + Inches(0.55), Inches(11.3), items, size=14.5, gap=Inches(0.46))
    slide_number(s, 2)
    set_notes(s, "The retail energy back office is usually a patchwork: a pricing sheet, a separate enrollment "
                 "tool, a billing system, a portfolio spreadsheet, and a collections process run out of email "
                 "and Excel. Every handoff between those systems is a place where errors creep in — and in a "
                 "thin-margin, heavily regulated business, those errors show up directly as lost margin, PUC "
                 "compliance exposure, customer complaints, and headcount spent on manual reconciliation. "
                 "ORBIC's premise is that these six-to-seven functions should run on one connected platform.")


# ── Slide 3 — Four operating engines ────────────────────────────────────────
def slide_03():
    s = add_slide()
    kicker(s, "The ORBIC Platform")
    title(s, "One platform. Four connected operating engines.")
    picture_fit(s, os.path.join(ASSETS, "four_engine_architecture.png"),
                Inches(0.5), Inches(1.55), Inches(12.35), Inches(5.45))
    slide_number(s, 3)
    set_notes(s, "ORBIC is organized around four operating engines that share one underlying data model: "
                 "Sales (pricing, brokers, contracts), Operations (enrollment, activation, billing, the "
                 "multi-meter portal), Portfolio (forecasting, hedging, risk), and Collections (delinquency "
                 "through legal escalation). Three layers run across all four engines rather than living "
                 "inside any single one: the AI operating layer (Orbi), the audit and control layer, and the "
                 "reporting and intelligence layer. The rest of this deck goes engine by engine, then covers "
                 "those three cross-cutting layers.")


# ── Slide 4 — Complete REP lifecycle ────────────────────────────────────────
def slide_04():
    s = add_slide()
    kicker(s, "End-to-End Lifecycle")
    title(s, "The complete REP lifecycle, on one data model", size=28)
    picture_fit(s, os.path.join(ASSETS, "lifecycle_pipeline.png"),
                Inches(0.35), Inches(1.55), Inches(12.65), Inches(5.5))
    slide_number(s, 4)
    set_notes(s, "A customer's journey through ORBIC is one continuous pipeline: the Sales Engine produces a "
                 "priced offer, which becomes a Contract Confirmation, which drives the Enrollment Engine "
                 "(MasterRoll generation, ERCOT switch), which activates into the Billing Engine (EDI 867/810 "
                 "ingestion, tax computation, invoicing), which feeds the Portfolio Engine (the enrolled load "
                 "is now part of the hedge book and risk position), and — when an account goes delinquent — "
                 "into Collections. Every stage writes to the same underlying tables (contract_renewal is the "
                 "single source of truth for an active contract), so nothing has to be manually re-entered "
                 "between stages, and AI, audit, and reporting all read from that same continuous record.")


# ── Slide 5/6/12 — Engine card grid helper ──────────────────────────────────
def engine_slide(n, kicker_txt, title_txt, cards, note):
    s = add_slide()
    kicker(s, kicker_txt)
    title(s, title_txt)
    cols = 3
    gap = Inches(0.22)
    cw = (Inches(11.93) - gap * (cols - 1)) / cols
    ch = Inches(2.3)
    x0, y0 = Inches(0.7), Inches(1.85)
    for i, (t, d, status) in enumerate(cards):
        col, row = i % cols, i // cols
        x = x0 + col * (cw + gap)
        y = y0 + row * (ch + gap)
        module_card(s, x, y, cw, ch, t, d, status)
    slide_number(s, n)
    set_notes(s, note)
    return s


def slide_05():
    cards = [
        ("Daily & Custom Pricing", "Daily pricing generation and custom quote workflows in the core "
         "application, covering the pricing screens sales teams use every day.", "built"),
        ("Broker Management", "Broker directory, ESI ID lookup, and commission tracking inside the core app.", "built"),
        ("Broker Portal & Application", "Standalone Orbic Broker Portal — real login, live renewal/expiration "
         "dashboard, and 13 PDF-generation forms (contracts, LOA, ACH, credit card, guarantee, credit check, "
         "account transfer, cancellation, meter add-on, payment plan).", "built"),
        ("Contract Management", "Contract tracking with expiring-contract alerts at 30- and 90-day horizons "
         "pulled from live renewal data.", "built"),
        ("Commission Management", "Commission calculation and downloadable commission reports for brokers.", "built"),
        ("Broker-Facing Quote Pricing Engine", "Automated daily-quote and custom-price generation directly "
         "inside the Broker Portal — the portal's own pricing endpoints are stubs today.", "roadmap"),
    ]
    engine_slide(5, "Engine 01 — Sales", "Sales Engine", cards,
                 "The Sales Engine covers everything from daily and custom pricing to broker relationships. "
                 "The core app's pricing and broker-management screens are built and in daily use. The Broker "
                 "Portal is a genuine standalone Next.js + FastAPI application (not a mock) with real "
                 "authentication and thirteen working PDF-generation forms covering the full paperwork set a "
                 "broker needs — contracts, LOA, ACH, credit card, guarantee, credit check, account transfer, "
                 "cancellation, meter add-on, and payment plan. The one gap: the Broker Portal's own "
                 "pricing-quote endpoints are stubbed and not yet wired to live pricing — that's an explicit, "
                 "known open item, not an oversight.")


def slide_06():
    cards = [
        ("Contract Confirmation", "Confirmation workflow that hands a signed offer into the enrollment pipeline.", "built"),
        ("Enrollment & MasterRoll", "Enrollment Engine supports six contract types and generates the "
         "128-column MasterRoll XLSX used for ERCOT switch submission, with active-contract guard rules.", "built"),
        ("Activation", "Activation writes contract_renewal as the single source of truth for an active contract.", "built"),
        ("Billing Engine", "Ingests EDI 867/810, matches contracts, computes tax, and produces invoices.", "built"),
        ("Multi-Meter Portal — Continuous Move-In / Move-Out", "Standalone app, own DB and JWT auth. Customers "
         "add, cancel, and confirm meters on an ongoing self-service basis — that workflow is the continuous "
         "move-in/move-out operation, with unit-number-aware records for multi-meter properties.", "built"),
        ("Payments", "Payment processing surfaces exist in the app but are marked upcoming in the product "
         "navigation itself.", "roadmap"),
    ]
    engine_slide(6, "Engine 02 — Operations", "Operations Engine", cards,
                 "Operations is the widest engine: contract confirmation, enrollment (with real MasterRoll "
                 "generation), activation, and billing are all built and verified against the enrollment and "
                 "billing rule documents and the live routers. The Multi-Meter Portal deserves its own callout "
                 "— it's a genuinely separate standalone application (own database, own JWT auth, own admin "
                 "panel) for customers managing many meters under one account. Continuous move-in/move-out is "
                 "not a separate, partially-built layer on top of it — the portal's add/cancel/confirm-meter "
                 "workflow (status codes for pending, add-requested, cancel-requested, failed, archived) *is* "
                 "that continuous operation, running today, including unit-number fields for multi-meter / "
                 "multi-unit properties. That's why it's folded into the same Built card rather than split out "
                 "as its own roadmap item. Payments processing is the one item here flagged 'soon' directly in "
                 "the product's own navigation.")


# ── Slide 7 — Portfolio and Risk Engine ─────────────────────────────────────
def slide_07():
    s = add_slide()
    kicker(s, "Engine 03 — Portfolio")
    title(s, "Portfolio and Risk Engine")
    picture_fit(s, os.path.join(ASSETS, "portfolio_risk_diagram.png"),
                Inches(0.4), Inches(1.55), Inches(12.55), Inches(5.5))
    slide_number(s, 7)
    set_notes(s, "The Portfolio Engine combines a four-layer load forecast (DNA baseline, ERCOT growth "
                 "factors, seasonal NOAA adjustment, and a live 7-day ERCOT LFC override — the seasonal layer "
                 "is the one piece still on the roadmap) with real trading and exposure tools: a Position "
                 "Screen, a hedge book, DAM purchase entry, and manual mark-to-market. The Risk Dashboard "
                 "combines four weighted factors — Position 40%, Price 25%, Customer 20%, Weather 15% — and "
                 "notably the Customer factor queries the Collections module directly for at-risk exposure, "
                 "which is a real code-level integration between the Portfolio and Collections engines, not "
                 "just a shared theme. Four nightly monitoring checkpoints (Mirror Test, Historical Backtest, "
                 "Energy Balance Sanity, Portfolio Ratio Check) run automatically. Live market-price feeds "
                 "(CME, ICE, Bloomberg) are explicitly not built — mark-to-market today is a manual, "
                 "API-ready process.")


# ── Slide 8 — ERCOT Price Forecasting ───────────────────────────────────────
def slide_08():
    s = add_slide()
    kicker(s, "Portfolio Engine — Market Forecasting")
    title(s, "ERCOT Price Forecasting", size=30)
    textbox(s, Inches(0.7), Inches(1.5), Inches(11.9), Inches(0.5),
            "A DAM price-distribution model layered on the existing load and weather forecasting engines.",
            size=14.5, color=MUTED)
    picture_fit(s, os.path.join(ASSETS, "price_forecasting_diagram.png"),
                Inches(0.5), Inches(2.05), Inches(12.35), Inches(4.9))
    slide_number(s, 8)
    set_notes(s, "The inputs on the left are real and already running: the net load forecast (load minus "
                 "wind/solar) built on the Portfolio Engine's four-layer forecast stack, historical DAM/RTM "
                 "settlement prices, and 8-zone weather data — all scraped directly from ERCOT and Open-Meteo "
                 "on a scheduled basis today. The new piece is a DAM price forecasting model layered on top of "
                 "that data: gradient-boosted quantile regression, chosen deliberately over a single point "
                 "forecast because ERCOT prices are heavy-tailed and spike risk matters more than the average "
                 "price. A dedicated ERCOT bid/offer-stack scrape is a planned input, not yet built — today's "
                 "scrapers cover settlement and clearing prices, not the underlying offer curves. The model "
                 "itself and its price-distribution output are roadmap items, presented honestly as such; they "
                 "are the direct input to the hedge ratio engine on the next slide.")


# ── Slide 9 — DAM/RTM Hedging Framework ─────────────────────────────────────
def slide_09():
    s = add_slide()
    kicker(s, "Portfolio Engine — Hedging Policy")
    title(s, "DAM/RTM Hedging Framework", size=28)
    textbox(s, Inches(0.7), Inches(1.5), Inches(11.9), Inches(0.5),
            "A risk-gated framework for the residual real-time exposure that remains after day-ahead "
            "procurement.", size=14.5, color=MUTED)
    picture_fit(s, os.path.join(ASSETS, "hedging_framework_diagram.png"),
                Inches(0.4), Inches(2.05), Inches(12.55), Inches(4.7))
    slide_number(s, 9)
    set_notes(s, "REPs procure close to 100% of forecasted load in the day-ahead market to meet their "
                 "load-serving obligation, but forecast drift between DAM close and real-time delivery still "
                 "leaves residual exposure in RTM. This framework governs that residual exposure only. The "
                 "policy has one absolute rule that overrides everything else: RTM is never left short, in any "
                 "hour, regardless of any spread signal — RTM risk is asymmetric and uncapped, and Winter Storm "
                 "Uri (February 2021) is the reference case for why that rule is non-negotiable. In hours the "
                 "model scores as low-risk — low net-load volatility, low spike probability — a reduced hedge "
                 "ratio is permitted specifically to capture the historical DAM-RTM spread; this is a "
                 "risk-managed exception gated by the risk score, not a standalone strategy. The Position "
                 "Screen, hedge book, and DAM purchase entry that this framework would act through are already "
                 "built (see the Portfolio Engine slide); the spread forecast, spike-risk score, and automated "
                 "hedge ratio engine itself are roadmap. Scope note: this framework covers energy (DAM/RTM) "
                 "only. ERCOT also allocates ancillary service costs to every load-serving entity by load "
                 "ratio share, and those can be hedged bilaterally ahead of delivery the same way energy can — "
                 "extending this framework to cover that ancillary-service exposure is planned, and the "
                 "underlying ERCOT AS price data is already being captured (see the Shadow Settlements slide).")


# ── Slide 10 — Backtested Performance (pending) ─────────────────────────────
def slide_10():
    s = add_slide()
    kicker(s, "Portfolio Engine — Market Forecasting")
    title(s, "Backtested Performance", size=30)
    textbox(s, Inches(0.7), Inches(1.5), Inches(11.9), Inches(0.5),
            "Quantitative validation is planned once the price forecasting model and hedging framework are "
            "built — no results exist yet.", size=14.5, color=MUTED)

    px, py, pw, ph = Inches(1.9), Inches(2.5), Inches(9.55), Inches(3.55)
    rect(s, px, py, pw, ph, fill=PANEL, line_color=BORDER, line_w=1.0, radius=0.06)
    status_pill(s, px + Inches(0.4), py + Inches(0.4), "roadmap", w=Inches(1.9), h=Inches(0.36))
    textbox(s, px + Inches(0.4), py + Inches(0.95), pw - Inches(0.8), Inches(0.5),
            "No backtest has been run — this slide is a placeholder for real results, not an estimate.",
            size=15, color=WHITE, bold=True)
    items = [
        "Cost savings versus a naive always-100%-DAM-hedge baseline, once the price forecasting model exists",
        "Risk-containment metrics — RTM exposure avoided in high-risk hours, spike-hour outcomes",
        "No cost-savings figures, accuracy percentages, or risk metrics are presented anywhere in this deck "
        "until they come from an actual backtest against historical ERCOT data",
    ]
    bullet_list(s, px + Inches(0.4), py + Inches(1.55), pw - Inches(0.8), items, size=13.5, gap=Inches(0.58))
    slide_number(s, 10)
    set_notes(s, "This slide is intentionally a placeholder. The DAM price forecasting model and the hedge "
                 "ratio engine described on the previous two slides do not exist in code yet, so there is no "
                 "backtest to report. Once they are built, the intended validation is a backtest against "
                 "historical ERCOT DAM/RTM data comparing this framework's cost outcome to a naive "
                 "always-100%-DAM-hedge baseline, alongside risk-containment metrics such as RTM exposure "
                 "avoided during high-risk hours. No placeholder numbers are shown here — per the same "
                 "verification discipline used throughout this deck, a claim is not made until it is real.")


# ── Slide 11 — Shadow Settlements ────────────────────────────────────────────
def slide_11():
    s = add_slide()
    kicker(s, "Portfolio Engine — Settlements")
    title(s, "Shadow Settlements", size=30)
    textbox(s, Inches(0.7), Inches(1.5), Inches(11.9), Inches(0.5),
            "A four-step reconciliation workflow that checks ORBIC's own billing math — energy and ancillary "
            "service costs — against ERCOT's settlement of record.", size=14.5, color=MUTED)
    picture_fit(s, os.path.join(ASSETS, "shadow_settlements_diagram.png"),
                Inches(0.5), Inches(2.05), Inches(12.35), Inches(4.9))
    slide_number(s, 11)
    set_notes(s, "Shadow Settlements is the discipline of independently estimating what ERCOT will bill (or "
                 "credit) a REP for a given period, then checking that estimate against ERCOT's actual "
                 "settlement statement. That statement is not energy alone — ERCOT also allocates ancillary "
                 "service costs to every load-serving entity by load ratio share, so an accurate estimate has "
                 "to account for both. The foundation is real: ERCOT settlement data (RTM Initial, Final, and "
                 "True-Up) already flows into the platform and feeds the Position Screen today, and ERCOT DAM "
                 "ancillary service clearing prices are already being scraped and stored on a scheduled basis "
                 "(`scraper_ercot_market_prices.py`, `ercot_dam_capacity_prices` table). Building the REP-side "
                 "settlement bill estimate from monthly usage and pricing data — including folding in that "
                 "ancillary cost allocation — is in progress. The comparison-to-actual, difference-"
                 "reconciliation, and two-way audit steps are roadmap items — this is deliberately presented "
                 "as a workflow being built, not a finished reconciliation engine, because that is the "
                 "accurate current state.")


# ── Slide 12 — Collections Engine ───────────────────────────────────────────
def slide_12():
    s = add_slide()
    kicker(s, "Engine 04 — Collections")
    title(s, "Collections Engine", size=30)
    textbox(s, Inches(0.7), Inches(1.5), Inches(11.9), Inches(0.5),
            "A full delinquency lifecycle with PUC-compliant notice timing and a human-approval gate on every "
            "irreversible action.", size=14.5, color=MUTED)
    picture_fit(s, os.path.join(ASSETS, "collections_lifecycle_diagram.png"),
                Inches(0.35), Inches(2.05), Inches(12.65), Inches(4.9))
    slide_number(s, 12)
    set_notes(s, "Collections is presented as a lifecycle, not a single past-due screen, because the code "
                 "supports that: accounts are auto-scored into delinquency tiers, DNP (Disconnect for "
                 "Non-Payment) notices are generated and gated by a hard-coded PUC 10-day rule (PUCT Subst. R. "
                 "25.480) before execution is even allowed, and every proposed action — DNP execution, an ETF "
                 "waiver, a payment plan, a write-off — routes through a human approval queue with a full "
                 "audit timeline. Move-out and legal-escalation/demand-letter actions are modeled in the same "
                 "schema but rely on a generic stage-change function rather than a dedicated workflow, so "
                 "they're marked partially built. The 'Collections Agent' as an autonomous actor is "
                 "infrastructure-ready — the tool registry, approval gating, and audit trail are all built — "
                 "but there is no live LLM invocation wired into collections today, confirmed by a repo-wide "
                 "search for LLM API usage.")


# ── Slide 13 — AI operating layer ───────────────────────────────────────────
def slide_13():
    s = add_slide()
    kicker(s, "Cross-Cutting Layer — AI")
    title(s, "AI Operating Layer")
    picture_fit(s, os.path.join(ASSETS, "ai_agent_diagram.png"),
                Inches(0.4), Inches(1.5), Inches(8.0), Inches(5.55))
    tx = Inches(8.6)
    textbox(s, tx, Inches(1.75), Inches(4.1), Inches(0.4), "In the app today", size=14, color=CYAN, bold=True, font=FONT_SEMI)
    bullet_list(s, tx, Inches(2.2), Inches(4.1), [
        "Orbi is a live, tool-calling agent wired to 12 real ORBIC endpoints",
        "Answers are grounded in production data — no invented figures",
        "Runs inside the core app end users already use",
    ], size=12.5, gap=Inches(0.55))
    textbox(s, tx, Inches(4.2), Inches(4.1), Inches(0.4), "Built, not yet merged", size=14, color=AMBER, bold=True, font=FONT_SEMI)
    bullet_list(s, tx, Inches(4.65), Inches(4.1), [
        "A separate operational email assistant (next slide) — built and tested standalone; integrating it into the main app is what remains",
        "Grounded in 15 years of founder-provided REP email correspondence — a real dataset, not an independently verified performance claim",
    ], size=12.5, gap=Inches(0.6), marker_color=AMBER)
    slide_number(s, 13)
    set_notes(s, "Orbi is the one confirmed, live LLM integration inside the ORBIC codebase itself: a tool-calling "
                 "agent with a grounding system prompt ('never invent data — always call a tool') wired to twelve "
                 "real endpoints spanning customers, pricing, brokers, forecasting, and past-due accounts. A "
                 "second, separate operational email assistant already exists as a working standalone pipeline "
                 "outside the main application — local retrieval over historical email correspondence feeding an "
                 "LLM drafting step, with a confidence gate that defers to a human instead of guessing. It has not "
                 "been merged into the main application yet, and that distinction is called out explicitly on the "
                 "next slide. The '15 years of REP operational experience' behind it is the real historical email "
                 "corpus the assistant is grounded in, provided by the founder — not an independently verified "
                 "accuracy or performance claim.")


# ── Slide 14 — Operational email assistant pipeline ──────────────────────────
def slide_14():
    s = add_slide()
    kicker(s, "Built, Not Yet Integrated — AI Layer")
    title(s, "Operational Email Assistant", size=28)
    textbox(s, Inches(0.7), Inches(1.45), Inches(11.9), Inches(0.4),
            "A working retrieval + drafting pipeline for inbound operational email — built and tested outside "
            "the main app, not yet merged into it.",
            size=14.5, color=MUTED)
    picture_fit(s, os.path.join(ASSETS, "email_pipeline_diagram.png"),
                Inches(0.35), Inches(1.95), Inches(12.65), Inches(5.0))
    slide_number(s, 14)
    set_notes(s, "This pipeline is real and working today as a standalone tool built separately from the ORBIC "
                 "application, not merely designed: incoming operational email is matched via local retrieval "
                 "(sentence-transformer embeddings over a persistent local vector store) against a base of real "
                 "historical query/reply pairs categorized into billing, payment, pricing, commission, "
                 "collections, and cancellation/closure. An LLM infers the category and drafts a reply grounded "
                 "in the retrieved historical replies, and a confidence gate withholds the draft — deferring to "
                 "a human — when the retrieved matches aren't similar enough or conflict with each other. The "
                 "specific box layout shown here (routing to per-category agents, human-intervention branch) "
                 "comes from a reference pipeline diagram used purely for its shape; no branding from that "
                 "source material appears anywhere in this deck. What's true today: the retrieval-and-drafting "
                 "core is built and has been tested against real historical email. What's not yet true: it has "
                 "not been merged into the ORBIC application — there is no live inbox connection or in-app "
                 "routing yet, which is the integration work that remains.")


# ── Slide 15 — Audit and control layer ──────────────────────────────────────
def slide_15():
    cards = [
        ("Enrollment Audit", "Dedicated enrollment-audit screen and workflow in the core application.", "built"),
        ("Billing Audit", "Dedicated billing-audit screen checking invoices against contract and usage data.", "built"),
        ("Payment Audit", "Dedicated payment-audit screen reconciling payments against billed amounts.", "built"),
        ("Tax & Process Audit Trail", "Tax computation (SPD3 / MGRT / PUCA) runs inside the Billing Engine "
         "with a traceable calculation path per invoice.", "built"),
        ("Commission Audit", "A dedicated commission-audit view beyond the existing commission report is not "
         "yet a separate product surface.", "roadmap"),
        ("Forecast Monitoring Checkpoints", "Four automated nightly checkpoints (Mirror Test, Historical "
         "Backtest, Energy Balance Sanity, Portfolio Ratio Check) that self-check the forecast pipeline.", "built"),
    ]
    engine_slide(15, "Cross-Cutting Layer — Audit", "Audit and Control Layer", cards,
                 "Audit is not an afterthought bolted onto ORBIC — enrollment, billing, and payment audits are "
                 "dedicated screens in the core navigation, and tax computation carries its own traceable "
                 "calculation path. Four automated nightly checkpoints continuously sanity-check the forecast "
                 "pipeline itself, which is a form of audit applied to the platform's own outputs, not just to "
                 "customer transactions. This discipline reflects lessons from real REP operations: the "
                 "specific checkpoints and audit points exist because they map to failure modes seen in "
                 "day-to-day retail energy operations, not generic software QA. The one gap called out "
                 "honestly here is a dedicated commission-audit surface, which does not yet exist beyond the "
                 "commission report itself. No specific savings or error-reduction figures are claimed for any "
                 "of these audits, since none have been independently verified.")


# ── Slide 16 — Reporting and intelligence layer ─────────────────────────────
def slide_16():
    s = add_slide()
    kicker(s, "Cross-Cutting Layer — Reporting")
    title(s, "Reporting and Intelligence Layer")
    steps = [
        ("1", "Specify report type & period", "PUC/ERCOT/EIA, settlements, cash, accounting, tax, lien "
         "evaluation, or an ad hoc management report"),
        ("2", "ORBIC generates the report", "Pulled live from the same underlying data model every engine "
         "writes to"),
        ("3", "Saved to the report library", "Versioned and retrievable — no re-running a one-off script to "
         "get the same report again"),
    ]
    n = len(steps)
    gap = Inches(0.4)
    w = (Inches(11.93) - gap * (n - 1)) / n
    h = Inches(2.1)
    x0, y0 = Inches(0.7), Inches(1.85)
    for i, (num, t, d) in enumerate(steps):
        x = x0 + i * (w + gap)
        rect(s, x, y0, w, h, fill=PANEL, line_color=BORDER, radius=0.07)
        textbox(s, x + Inches(0.22), y0 + Inches(0.12), w - Inches(0.44), Inches(0.55), num,
                size=26, color=CYAN, bold=True, font=FONT_SEMI)
        textbox(s, x + Inches(0.22), y0 + Inches(0.7), w - Inches(0.44), Inches(0.5), t,
                size=14.5, color=WHITE, bold=True, font=FONT_SEMI)
        textbox(s, x + Inches(0.22), y0 + Inches(1.18), w - Inches(0.44), Inches(0.85), d,
                size=11.5, color=MUTED, line_spacing=1.12)
        if i < n - 1:
            textbox(s, x + w, y0 + h / 2 - Inches(0.2), gap, Inches(0.4), "→", size=22,
                    color=CYAN, align=PP_ALIGN.CENTER, anchor=MSO_ANCHOR.MIDDLE)
    status_pill(s, x0, y0 + h + Inches(0.3), "progress", w=Inches(2.4), h=Inches(0.36))
    textbox(s, x0 + Inches(2.6), y0 + h + Inches(0.3), Inches(9.3), Inches(0.36),
            "Report-generation module is structured and in progress — it is flagged directly in the product's "
            "own navigation as an upcoming feature.", size=12.5, color=MUTED, anchor=MSO_ANCHOR.MIDDLE)
    slide_number(s, 16)
    set_notes(s, "The reporting layer is designed as a simple three-step flow: a user specifies what they need "
                 "and for what period, ORBIC generates it from the live data model, and it lands in a "
                 "persistent report library. The intended category list spans regulatory (PUC/ERCOT/EIA), "
                 "settlements, cash management, accounting, taxes, lien evaluation, and ad hoc management "
                 "reports. This module is honestly labeled in progress — the product's own navigation flags "
                 "Reports as an upcoming feature rather than a shipped one, so it is not presented here as "
                 "complete.")


# ── Slide 17 — Market opportunity ───────────────────────────────────────────
def slide_17():
    s = add_slide()
    kicker(s, "Market Opportunity")
    title(s, "A large, underserved long tail of small-to-mid REPs", size=26)

    stats = [
        ("140", "PUCT-certified REPs operating in ERCOT today", CYAN),
        ("63–78%", "of Texas residential share held by just the top 3 incumbents — "
         "everyone else is long tail", AMBER),
        ("13 states + DC", "have residential retail choice nationally — ERCOT is the "
         "beachhead, not the ceiling", BLUE),
    ]
    cols = 3
    gap = Inches(0.22)
    cw = (Inches(11.93) - gap * (cols - 1)) / cols
    ch = Inches(1.75)
    x0, y0 = Inches(0.7), Inches(1.65)
    for i, (num, label, accent) in enumerate(stats):
        x = x0 + i * (cw + gap)
        rect(s, x, y0, cw, ch, fill=PANEL, line_color=BORDER, line_w=1.0, radius=0.06)
        rect(s, x, y0, cw, Inches(0.06), fill=accent)
        textbox(s, x + Inches(0.24), y0 + Inches(0.2), cw - Inches(0.48), Inches(0.65),
                num, size=28, color=WHITE, bold=True, font=FONT_SEMI)
        textbox(s, x + Inches(0.24), y0 + Inches(0.88), cw - Inches(0.48), Inches(0.75),
                label, size=11.5, color=MUTED, line_spacing=1.12)

    py = y0 + ch + Inches(0.3)
    box_h = Inches(2.6)
    rect(s, Inches(0.7), py, Inches(11.93), box_h, fill=PANEL, line_color=BORDER, line_w=1.0, radius=0.05)
    textbox(s, Inches(0.95), py + Inches(0.2), Inches(11.4), Inches(0.4),
            "ORBIC Pricing — Target Segment: REPs with 0–50k Meters", size=14.5, color=WHITE,
            bold=True, font=FONT_SEMI)
    rows = [
        ("Under 10,000 meters", "$2.50 / meter / month"),
        ("10,000+ meters", "$2.00 / meter / month"),
    ]
    ry = py + Inches(0.75)
    for label, price in rows:
        textbox(s, Inches(0.95), ry, Inches(6.5), Inches(0.4), label, size=13, color=MUTED)
        textbox(s, Inches(7.5), ry, Inches(4.13), Inches(0.4), price, size=13, color=CYAN, bold=True,
                align=PP_ALIGN.RIGHT)
        ry += Inches(0.42)
    textbox(s, Inches(0.95), ry + Inches(0.08), Inches(11.1), Inches(0.4),
            "→ $150K–$1.2M ARR per REP across the 5k–50k meter target range",
            size=13.5, color=GREEN, bold=True)
    textbox(s, Inches(0.95), ry + Inches(0.48), Inches(11.1), Inches(0.35),
            "Illustrative, based on ORBIC's own stated pricing — not a market-size figure.",
            size=10.5, color=MUTED2, italic=True)
    slide_number(s, 17)
    set_notes(s, "The 140-REP figure is the PUCT's own directory of certified retail electric providers "
                 "doing business in ERCOT today — that is the immediately addressable universe, not a "
                 "projection. The 63–78% concentration figure comes from published market-structure research "
                 "on Texas residential retail (NRG Energy, Vistra, and Direct Energy holding that combined "
                 "share) — the point is structural, not a knock on those companies: REPs at that scale "
                 "build software in-house, so they are not ORBIC's buyer. Everyone below them — the large "
                 "majority of the 140 — is the long tail this pricing and segment target is built for. The "
                 "13-states-plus-DC figure (RESA) establishes that ERCOT is a beachhead within a larger "
                 "national footprint of residential choice, not the total addressable ceiling. The pricing "
                 "block is ORBIC's own stated go-to-market pricing, not a sourced market statistic, and the "
                 "resulting ARR-per-REP range is explicitly labeled illustrative unit economics — not a "
                 "revenue forecast, consistent with this deck's rule against inventing market-size or revenue "
                 "figures.")


# ── Slide 18 — Competitive landscape ────────────────────────────────────────
def slide_18():
    s = add_slide()
    kicker(s, "Competitive Landscape")
    title(s, "Full-stack platforms are arriving — none built for the small/mid REP", size=24)
    items = [
        ("VertexOne / VXretail", "CIS & billing incumbent — 400+ cloud customers; named live ERCOT REP "
         "customers (Graviti Power, Gridmatic Retail, Summer Energy Northeast).",
         "Billing/CIS only — no integrated portfolio, risk, or AI layer."),
        ("Kraken Technologies (Octopus Energy)", "Global full-stack platform — signed a 5-year deal with "
         "Champion Energy Services (2025) to bring Kraken into Texas residential.",
         "Entering via one large enterprise account — not priced or built for the 0–50k meter segment."),
        ("Ascend Analytics / Enverus / ZE PowerGroup", "ETRM and risk-analytics point solutions — hedging, "
         "forecasting, and trading analytics only.",
         "No CIS, billing, or collections — REPs must stitch these together with a separate billing vendor."),
    ]
    row_h = Inches(1.45)
    gap = Inches(0.15)
    y = Inches(1.6)
    for name, fact, gap_txt in items:
        rect(s, Inches(0.7), y, Inches(11.93), row_h, fill=PANEL, line_color=BORDER, line_w=1.0, radius=0.05)
        rect(s, Inches(0.7), y, Inches(0.06), row_h, fill=CYAN)
        textbox(s, Inches(0.95), y + Inches(0.14), Inches(11.4), Inches(0.4), name, size=15,
                color=WHITE, bold=True, font=FONT_SEMI)
        textbox(s, Inches(0.95), y + Inches(0.54), Inches(11.4), Inches(0.45), fact, size=12,
                color=MUTED, line_spacing=1.1)
        textbox(s, Inches(0.95), y + Inches(0.98), Inches(11.4), Inches(0.42),
                "Gap for ORBIC: " + gap_txt, size=12, color=AMBER, line_spacing=1.1)
        y += row_h + gap
    textbox(s, Inches(0.7), y + Inches(0.08), Inches(11.93), Inches(0.5),
            "ORBIC: full-stack like Kraken, sized and priced for the small/mid REP segment VertexOne "
            "serves piecemeal and Kraken hasn't chased.",
            size=13, color=CYAN, italic=True, align=PP_ALIGN.CENTER)
    slide_number(s, 18)
    set_notes(s, "Each row is a named, sourced competitor, not a category invented for this slide. VertexOne "
                 "is the clearest direct comparable — it is the market's recognized CIS/billing leader with "
                 "named, live ERCOT REP customers, but its product is billing/CIS-centric with no evidence of "
                 "an integrated portfolio, risk, or AI layer. Kraken Technologies matters because it confirms "
                 "a global full-stack platform is already entering Texas — its 2025 deal with Champion "
                 "Energy Services is real and public — but that entry is through one large enterprise "
                 "account, which is a different motion and a different price point than the 0–50k meter "
                 "segment ORBIC targets. Ascend Analytics, Enverus, and ZE PowerGroup represent the ETRM/risk "
                 "point-solution category that today's fragmented REP stacks lean on — they are evidence "
                 "for the 'stitched together, not integrated' problem this deck opens with, not a claim that "
                 "ORBIC's forecasting or hedging tooling has been benchmarked against them.")


# ── Slide 19 — Go-to-market ──────────────────────────────────────────────────
def slide_19():
    s = add_slide()
    kicker(s, "Go-to-Market")
    title(s, "Proven in production. Focused on the segment incumbents ignore.", size=24)
    cards = [
        ("Track Record", "15 years running a real, operating ERCOT REP's full stack — proven in "
         "production, not a prototype."),
        ("Target Segment", "REPs with 0–50k meters — below the scale where incumbents build in-house, "
         "below where enterprise CIS vendors focus."),
        ("Direct Sales", "Outbound to REP ops, finance, and executive leadership — the buyers who feel "
         "disconnected systems every day."),
        ("Broker Channel", "The built Broker Portal already gives brokers — who touch multiple REPs at "
         "once — a reason to be in the platform, creating a channel into their REP relationships."),
    ]
    cols = 2
    gap = Inches(0.25)
    cw = (Inches(11.93) - gap) / 2
    ch = Inches(1.95)
    x0, y0 = Inches(0.7), Inches(1.7)
    for i, (t, d) in enumerate(cards):
        col, row = i % cols, i // cols
        x = x0 + col * (cw + gap)
        y = y0 + row * (ch + Inches(0.25))
        rect(s, x, y, cw, ch, fill=PANEL, line_color=BORDER, line_w=1.0, radius=0.06)
        rect(s, x, y, Inches(0.06), ch, fill=CYAN)
        textbox(s, x + Inches(0.24), y + Inches(0.18), cw - Inches(0.48), Inches(0.4), t, size=15,
                color=WHITE, bold=True, font=FONT_SEMI)
        textbox(s, x + Inches(0.24), y + Inches(0.62), cw - Inches(0.48), ch - Inches(0.8), d, size=12,
                color=MUTED, line_spacing=1.15)
    textbox(s, Inches(0.7), Inches(6.05), Inches(11.93), Inches(0.5),
            "Usage-based pricing ($2.00–$2.50 / meter / month) lowers the barrier to a pilot versus a "
            "multi-year enterprise CIS contract.",
            size=13, color=GREEN, bold=True, align=PP_ALIGN.CENTER)
    slide_number(s, 19)
    set_notes(s, "The track record claim is deliberately past tense and deliberately does not name the "
                 "specific REP: this platform was built and operated for fifteen years running a real "
                 "ERCOT retail energy provider's full operation — sales, enrollment, billing, portfolio, "
                 "and collections — which is why the engine-by-engine slides in this deck can point to "
                 "real production code and real workflows rather than a demo. It is presented as proof of "
                 "production maturity, not as an active reference account. The target segment (0–50k "
                 "meters) is a deliberate choice, not a limitation: it is the space below where the top "
                 "incumbents build in-house and below where an enterprise CIS vendor like VertexOne's larger "
                 "accounts focus. Distribution is two motions: direct sales to REP leadership, and a broker "
                 "channel — the second one is not aspirational, it leans on the Broker Portal that is "
                 "already built and already gives brokers, who by definition touch multiple REPs, a reason "
                 "to be inside the platform.")


# ── Slide 20 — Defensibility ─────────────────────────────────────────────────
def slide_20():
    s = add_slide()
    kicker(s, "Why It's Hard to Replicate")
    title(s, "Defensibility")
    items = [
        ("Integrated, not stitched together", "Sales, enrollment, billing, portfolio, and collections read and "
         "write the same underlying data model — contract_renewal is the single source of truth from "
         "activation through billing."),
        ("Domain-specific operational rules encoded in the product", "PUC's 10-day DNP notice rule is "
         "enforced in code before an execution path is even reachable, not left to a spreadsheet or a "
         "person's memory."),
        ("Cross-engine intelligence", "The Risk Dashboard's Customer factor queries the Collections module "
         "directly — portfolio risk scoring is informed by real receivables exposure, not a static estimate."),
        ("Audit checkpoints built into daily operation", "Four nightly self-checks on the forecast pipeline "
         "itself, plus dedicated enrollment, billing, and payment audit screens."),
        ("AI grounded in operational workflows", "Orbi is wired to real production endpoints with an explicit "
         "no-invented-data grounding rule, not a generic chatbot layered on top."),
        ("Distinct, purpose-built products for hard sub-problems", "The Broker Portal and the Multi-Meter "
         "Portal are standalone applications solving broker paperwork and multi-meter management specifically "
         "— not generic screens repurposed for the job."),
    ]
    y = Inches(1.75)
    for t, d in items:
        rect(s, Inches(0.7), y, Inches(0.09), Inches(0.09), fill=CYAN, radius=0.5)
        textbox(s, Inches(0.98), y - Inches(0.05), Inches(11.3), Inches(0.35), t, size=14.5,
                color=WHITE, bold=True, font=FONT_SEMI)
        textbox(s, Inches(0.98), y + Inches(0.32), Inches(11.3), Inches(0.55), d, size=12,
                color=MUTED, line_spacing=1.1)
        y += Inches(0.85)
    slide_number(s, 20)
    set_notes(s, "The case for defensibility here is architectural and operational, not a claim about "
                 "proprietary data volume or model performance — neither of those has been independently "
                 "verified, so neither is claimed. What is verifiable in the code: one shared data model "
                 "across engines, regulatory rules enforced at the code level rather than left to process "
                 "discipline, a risk engine that reads live collections exposure, audit checkpoints that run "
                 "nightly against the platform's own forecasts, an AI layer grounded in real endpoints, and "
                 "two genuinely separate purpose-built products (Broker Portal, Multi-Meter Portal) for two of "
                 "the hardest operational sub-problems in this business.")


# ── Slide 21 — Product maturity ─────────────────────────────────────────────
def slide_21():
    s = add_slide()
    kicker(s, "Honest Status")
    title(s, "Product Maturity")
    rows = [
        ("Sales capabilities (pricing, contracts, commission)", "built"),
        ("Broker Portal & application", "built"),
        ("Enrollment Engine & MasterRoll", "built"),
        ("Multi-Meter Portal", "built"),
        ("Billing Engine (EDI ingestion → tax → invoice)", "built"),
        ("Portfolio forecasting (DNA / growth / LFC layers)", "built"),
        ("7-Day LFC override", "built"),
        ("Monitoring checkpoints (4 nightly checks)", "built"),
        ("Manual mark-to-market", "built"),
        ("Shadow Settlements (estimate → compare → reconcile → audit)", "progress"),
        ("Collections Agent (autonomous LLM actor)", "roadmap"),
        ("Operational email assistant (standalone pipeline)", "partial"),
        ("Operational email assistant — merged into ORBIC", "roadmap"),
        ("Report generation & library", "progress"),
        ("Seasonal NOAA forecast layer", "roadmap"),
        ("Live MTM market-price feeds", "roadmap"),
        ("ERCOT MIS / SMT automation", "roadmap"),
    ]
    n = len(rows)
    per_col = (n + 1) // 2
    col_w = Inches(5.95)
    gap_x = Inches(0.3)
    row_h = Inches(0.42)
    y0 = Inches(1.75)
    for i, (label, status) in enumerate(rows):
        col = i // per_col
        row = i % per_col
        x = Inches(0.7) + col * (col_w + gap_x)
        y = y0 + row * row_h
        textbox(s, x, y, col_w - Inches(1.95), row_h, label, size=12, color=WHITE,
                anchor=MSO_ANCHOR.MIDDLE, line_spacing=1.0)
        status_pill(s, x + col_w - Inches(1.85), y + Inches(0.03), status, w=Inches(1.85), h=Inches(0.32))
    slide_number(s, 21)
    set_notes(s, "This matrix is the single source of truth for what is built versus in progress versus "
                 "roadmap, and it should be read alongside the README's verified-claims table, which cites the "
                 "specific file or router behind every one of these labels. Nothing here is rounded up: "
                 "Shadow Settlements and report generation are marked in progress rather than built because "
                 "their core reconciliation/report-generation logic isn't complete yet, even though supporting "
                 "pieces exist. The operational email assistant is split into two rows deliberately: the "
                 "standalone pipeline itself (local retrieval + LLM drafting, confidence-gated) is real, working, "
                 "tested code, so it is marked partially built rather than roadmap — but merging it into the "
                 "ORBIC application is separate, unstarted work and is marked roadmap on its own line. The "
                 "Collections Agent (an autonomous LLM actor across the delinquency-to-legal lifecycle), seasonal "
                 "NOAA forecasting, live MTM feeds, and ERCOT MIS/SMT automation remain roadmap — real "
                 "infrastructure exists for some of them (especially Collections), but the specific capability "
                 "named here is not live.")


# ── Slide 22 — Closing vision ────────────────────────────────────────────────
def slide_22():
    s = add_slide()
    picture_fit(s, os.path.join(ASSETS, "hero_graphic.png"), 0, 0, SW, SH)
    kicker(s, "Vision", y=Inches(1.4))
    textbox(s, Inches(0.7), Inches(1.8), Inches(10.5), Inches(1.4),
            "ORBIC becomes the operating layer for retail energy providers",
            size=32, color=WHITE, bold=True, font=FONT_SEMI, line_spacing=1.05)
    items = [
        "Daily decision support across sales, operations, portfolio, and collections",
        "Deeper audit and forecasting intelligence built directly into the platform",
        "Settlement intelligence that closes the loop between billing and ERCOT settlement",
        "A collections lifecycle that scales without scaling headcount",
        "AI-assisted operations grounded in the same data the business runs on",
    ]
    bullet_list(s, Inches(0.7), Inches(3.5), Inches(9.5), items, size=15, gap=Inches(0.5))
    slide_number(s, 22)
    set_notes(s, "The direction from here is expansion along the same four-engine spine rather than a pivot: "
                 "more decision support inside Sales and Portfolio, closing the loop on Shadow Settlements, "
                 "scaling Collections without proportional headcount growth via the approval-gated agent "
                 "infrastructure already built, and extending the AI operating layer from a single in-app "
                 "assistant into the broader operational surface area (starting with merging in the "
                 "already-built standalone email assistant). The goal is for ORBIC to be the system a retail "
                 "energy provider runs its business on, not a dashboard sitting next to the systems that "
                 "actually run it.")


def main():
    slide_01()
    slide_02()
    slide_03()
    slide_04()
    slide_05()
    slide_06()
    slide_07()
    slide_08()
    slide_09()
    slide_10()
    slide_11()
    slide_12()
    slide_13()
    slide_14()
    slide_15()
    slide_16()
    slide_17()
    slide_18()
    slide_19()
    slide_20()
    slide_21()
    slide_22()
    prs.save(OUT)
    print("Saved", OUT, "-", len(prs.slides._sldIdLst), "slides")


if __name__ == "__main__":
    main()
