-- Migration 004: ERCOT 810_02 charge code reference table
-- Source: SAC04-Codes-list_Oct2022.xlsx, sheet "810_02" (213 rows)
-- 810_03 sheet intentionally excluded - out of scope per ERCOT Protocols Section 19.3.1
-- implementation_date: datetime values converted to YYYY-MM-DD
--   "effective MM/DD/YYYY" strings parsed to proper dates, blanks stored as NULL

CREATE TABLE IF NOT EXISTS `ercot_charge_code_reference` (
  `code`                  VARCHAR(20)  NOT NULL,
  `description`           VARCHAR(255) NOT NULL,
  `market_description`    VARCHAR(500) DEFAULT NULL,
  `implementation_date`   DATE         DEFAULT NULL,
  `change_control_number` VARCHAR(50)  DEFAULT NULL,
  PRIMARY KEY (`code`),
  INDEX `idx_description` (`description`(50))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ercot_charge_code_reference`
  (`code`,`description`,`market_description`,`implementation_date`,`change_control_number`)
VALUES
  ('ADJ006','Franchise Fee Adjustment','Franchise Fee Adjustment',NULL,NULL),
  ('ADJ007','Franchise Surcharge Debit','Franchise Surcharge Debit',NULL,NULL),
  ('ADJ008','Franchise Surcharge Credit','Franchise Surcharge Credit',NULL,NULL),
  ('BAS001','Customer Charge','Basic Customer Charge',NULL,NULL),
  ('BAS003','Metering Charge','Delivery Point Charge',NULL,NULL),
  ('CRE020','Meter Owner Credit',NULL,NULL,NULL),
  ('CRE027','Utility Service Quality - System Performance Credit',NULL,NULL,NULL),
  ('CRE028','Utility Service Quality - Circuit Performance Credit',NULL,NULL,NULL),
  ('CRE029','Utility Service Quality – Connect Service Performance Credit',NULL,NULL,NULL),
  ('CRE030','Utility Service Quality - Other Credit','Utility Service Quality - Connect Service Performance Credit  Used to communicate TDSP Service Quality Credit for non-specific credit allowances SAC 15 (Description) required when using this code.',NULL,NULL),
  ('CRE031','Utility Service Quality - Other Credit','Used to communicate TDSP Service Quality Credit for non-specific credit allowances SAC 15 (Description) required when using this code.',NULL,NULL),
  ('DIS001','Distribution System Charge','Distribution Charge',NULL,NULL),
  ('DIS004','Transport Charge (XFMR)','Charge for transporting energy',NULL,NULL),
  ('DMD001','Demand Charge','Used to transmit budge or levelized amounts to the MC TDSP for inclusion on the consolidated bill',NULL,NULL),
  ('DSC001','Transition Charge-Off Allowance','Used only when IT 109 = B2B Discount for Charge-Off Allowance for TC',NULL,NULL),
  ('DSC002','Transition Charge-Off Allowance (COA2)','Used only when IT 109 = B2B Discount for Charge-Off Allowance for TC2',NULL,NULL),
  ('DSC003','Transition Charge-Off Allowance (COA3)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC3',NULL,NULL),
  ('DSC004','Transition Charge-Off Allowance (COA4)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC4',NULL,NULL),
  ('DSC005','State College and University Discount',NULL,NULL,NULL),
  ('DSC006','Transition Charge-Off Allowance (COA5)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC5','2011-02-21','CC2010-750'),
  ('DSC007','Transition Charge-Off Allowance (COA6)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC6','2011-02-21','CC2010-750'),
  ('DSC008','Transition Charge-Off Allowance (COA7)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC7','2011-02-21','CC2010-750'),
  ('DSC009','Transition Charge-Off Allowance (COA8)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC8','2011-02-21','CC2010-750'),
  ('DSC010','Transition Charge-Off Allowance (COA9)','Used only when IT109 = B2B Discount for Charge-Off Allowance for TC9','2011-02-21','CC2010-750'),
  ('FAC001','Additional Facilities','Equipment and Service Charge',NULL,NULL),
  ('FFR001','Non Metered Service','Non Metered Service',NULL,NULL),
  ('FUE001','Fuel Adjustment','Fuel Adjustment',NULL,NULL),
  ('INT001','Interest charged to the CR by the TDSP for disputed invoices.','Interest on Sale  Used only when IT109 = B2B',NULL,NULL),
  ('INT003','Interest paid by the TDSP to the CR on improperly invoiced charges','ITC Adjustment Interest   Used only when IT 109 = B2B',NULL,NULL),
  ('LAA001','Billed for Work performed Labor/Material','Billing for Work Done',NULL,NULL),
  ('LPC001','Late Payment Charge','Late Payment Charge  Use only when IT109 = B2B',NULL,NULL),
  ('MSC007','Property Damage','Property Damage',NULL,NULL),
  ('MSC010','Select Read Cycle Monthly Fee','Select Read Cycle Monthly Fee',NULL,NULL),
  ('MSC022','Competition Transition Charge (CTC)','Competition Transition Charge',NULL,NULL),
  ('MSC023','Competition Transition Charge (CTC2)','Competition Transition Charge 2',NULL,NULL),
  ('MSC024','System Benefit Fund (SBF)','Public Purpose Program',NULL,NULL),
  ('MSC025','Nuclear Decommissioning (NDF)','Nuclear Decommissioning',NULL,NULL),
  ('MSC029','Transition Charge','Charge applies to the recovery of the securitized portion of stranded regulatory assets and stranded costs',NULL,NULL),
  ('MSC030','Returned Instrument',NULL,NULL,NULL),
  ('MSC031','Non-Standard Communication',NULL,NULL,NULL),
  ('MSC032','Copying',NULL,NULL,NULL),
  ('MSC033','Special Metering & Non-Standard Metering Reports',NULL,NULL,NULL),
  ('MSC034','Special Products/Services',NULL,NULL,NULL),
  ('MSC035','Special Billing Service',NULL,NULL,NULL),
  ('MSC036','Transition Charge (TC2)','Charge applies to the recovery of securitized regulatory assets and stranded costs',NULL,NULL),
  ('MSC037','Transition Charge (TC3)','Charge applies to the recovery of  securitized regulatory assets and stranded costs',NULL,NULL),
  ('MSC038','Transition Charge (TC4)','Charge applies to the recovery of  securitized regulatory assets and stranded costs',NULL,NULL),
  ('MSC039','Advanced Metering Cost Recovery Factor',NULL,NULL,NULL),
  ('MSC040','Underground Facilities Surcharge',NULL,NULL,NULL),
  ('MSC041','Energy Efficiency Cost Recovery Factor (EECRF)',NULL,'2011-02-21','CC2008-726'),
  ('MSC042','Distribution Cost Recovery Factor',NULL,'2011-02-21','CC2010-750'),
  ('MSC043','Transition Charge (TC5)','Charge applies to the recovery of  securitized regulatory assets and stranded costs','2011-02-21','CC2010-750'),
  ('MSC044','Transition Charge (TC6)','Charge applies to the recovery of  securitized regulatory assets and stranded costs','2011-02-21','CC2010-750'),
  ('MSC045','Transition Charge (TC7)','Charge applies to the recovery of  securitized regulatory assets and stranded costs','2011-02-21','CC2010-750'),
  ('MSC046','Transition Charge (TC8)','Charge applies to the recovery of  securitized regulatory assets and stranded costs','2011-02-21','CC2010-750'),
  ('MSC047','Transition Charge (TC9)','Charge applies to the recovery of  securitized regulatory assets and stranded costs','2011-02-21','CC2010-750'),
  ('MSC048','Competition Transition Charge (CTC3)','Competition Transition Charge 3','2011-02-21','CC2010-750'),
  ('MSC049','Rate Case Expenses Surcharge',NULL,'2011-02-21','CC2010-750'),
  ('MSC050','Intelligent Grid Cost Recovery',NULL,'2011-02-21','CC2010-750'),
  ('MSC051','Vegetation Management',NULL,'2011-02-21','CC2010-750'),
  ('MSC052','System Hardening Tracking',NULL,'2011-02-21','CC2010-750'),
  ('MSC053','Deferred Tax Accounting Tracker',NULL,'2011-02-21','CC2010-750'),
  ('MSC054','RATE CASE EXPENSE SURCHARGE 2',NULL,'2012-01-01','CC2011-791'),
  ('MSC055','Surcharge Energy Efficiency','Compliance with PUCT Docket 42359','2014-09-01','CC2014-803'),
  ('MSC056','Deferred Cost Recovery Charge',NULL,'2016-09-19','CC2016-804'),
  ('MSC057','Temporary Emergency Electric Energy Facilities (TEEEF)',NULL,'2022-10-11','CC2022-839'),
  ('ODL002','Street Lighting - Point of Delivery',NULL,NULL,NULL),
  ('ODL003','Street Lighting - Facilities',NULL,NULL,NULL),
  ('ODL004','Street Lighting',NULL,NULL,NULL),
  ('ODL005','Outdoor Lighting - Facilities',NULL,NULL,NULL),
  ('ODL006','Outdoor Lighting - Asset Recovery',NULL,NULL,NULL),
  ('ODL007','Outdoor Lighting - (Guard Light) Extra Span Charge',NULL,NULL,NULL),
  ('OPT001','Non-Standard Metering Monthly Fee','Compliance with PUCT Substantive Rule 25.133','2013-10-16','CC2013-801'),
  ('PCR001','Power Cost Recovery Factor Reconciliation','In support of PUCT Docket 41474','2013-10-16','CC2013-802'),
  ('RRR001','Excess Mitigation Credit','State / Intrastate',NULL,NULL),
  ('RRR006','Rate Reduction Credit','Regulatory Commission Mandated Refund',NULL,NULL),
  ('RRR008','Merger Savings Credit',NULL,NULL,NULL),
  ('SER001','Service Charge (TDSP Specific Discretionary)','Used to communicate TDSP Service Quality Credit for non-specific credit allowances SAC 15 (Description) required when using this code.',NULL,NULL),
  ('SER009','Account Initiation',NULL,NULL,NULL),
  ('SER010','Special Meter Read',NULL,NULL,NULL),
  ('SER011','Out of Cycle Meter Reading - Regular Hours',NULL,NULL,NULL),
  ('SER012','Out of Cycle Meter Reading - Outside Regular Hours - Non-Holiday',NULL,NULL,NULL),
  ('SER013','Out of Cycle Meter Reading - Outside Regular Hours – Holiday',NULL,NULL,NULL),
  ('SER014','Connection Charge - Self Contained Meter',NULL,NULL,NULL),
  ('SER015','Connection Charge - Other Connections -Labor',NULL,NULL,NULL),
  ('SER016','Connection Charge - Other Connections -Transportation',NULL,NULL,NULL),
  ('SER017','Connection Charge - Other Connections-Material',NULL,NULL,NULL),
  ('SER018','Connection Charge - Other Connections -Other',NULL,NULL,NULL),
  ('SER019','Service Connection',NULL,NULL,NULL),
  ('SER020','Retail Customer Requested Clearance - Labor',NULL,NULL,NULL),
  ('SER021','Retail Customer Requested Clearance - Transportation',NULL,NULL,NULL),
  ('SER022','Retail Customer Requested Clearance - Material',NULL,NULL,NULL),
  ('SER023','Retail Customer Requested Clearance - Other',NULL,NULL,NULL),
  ('SER024','Disconnect at Meter',NULL,NULL,NULL),
  ('SER025','Disconnect Visit Charge',NULL,NULL,NULL),
  ('SER026','Disconnect at Pole, Weatherhead or Secondary Box',NULL,NULL,NULL),
  ('SER027','Priority Disconnect',NULL,NULL,NULL),
  ('SER028','Reconnect',NULL,NULL,NULL),
  ('SER029','Priority Reconnect',NULL,NULL,NULL),
  ('SER030','Reconnect at Meter Regular Hours - Regular Route',NULL,NULL,NULL),
  ('SER031','Reconnect at Meter Regular Hours - Special Route',NULL,NULL,NULL),
  ('SER032','Reconnect at Meter Outside Regular Hours - Non-Holiday',NULL,NULL,NULL),
  ('SER033','Reconnect at Meter Outside Regular Hours - Holiday',NULL,NULL,NULL),
  ('SER034','Reconnect at Pole, Weatherhead or Secondary Box - Regular Hours',NULL,NULL,NULL),
  ('SER035','Reconnect at Pole, Weatherhead or Secondary Box - Outside Regular Hours - Non-Holiday',NULL,NULL,NULL),
  ('SER036','Reconnect at Pole, Weatherhead or Secondary Box - Outside Regular Hours - Holiday',NULL,NULL,NULL),
  ('SER037','Delivery System Facilities Installation - Labor',NULL,NULL,NULL),
  ('SER038','Delivery System Facilities Installation - Transportation',NULL,NULL,NULL),
  ('SER039','Delivery System Facilities Installation - Material',NULL,NULL,NULL),
  ('SER040','Delivery System Facilities Installation - Other',NULL,NULL,NULL),
  ('SER041','Additional Service Design - Labor',NULL,NULL,NULL),
  ('SER042','Additional Service Design - Transportation',NULL,NULL,NULL),
  ('SER043','Additional Service Design - Material',NULL,NULL,NULL),
  ('SER044','Additional Service Design - Other',NULL,NULL,NULL),
  ('SER045','Temporary Facilities A ( add description in gray box)',NULL,NULL,NULL),
  ('SER046','Temporary Facilities B ( add description in gray box)',NULL,NULL,NULL),
  ('SER047','Temporary Facilities C ( add description in gray box)',NULL,NULL,NULL),
  ('SER048','Temporary Facilities D - Labor ( add description in gray box)',NULL,NULL,NULL),
  ('SER049','Temporary Facilities D - Transportation ( add description in gray box)',NULL,NULL,NULL),
  ('SER050','Temporary Facilities D - Material ( add description in gray box)',NULL,NULL,NULL),
  ('SER051','Temporary Facilities D - Other ( add description in gray box)',NULL,NULL,NULL),
  ('SER052','Underground Bypass Cable',NULL,NULL,NULL),
  ('SER053','Temporary Service',NULL,NULL,NULL),
  ('SER054','Facilities Relocation / Removal - Labor',NULL,NULL,NULL),
  ('SER055','Facilities Relocation / Removal - Transportation',NULL,NULL,NULL),
  ('SER056','Facilities Relocation / Removal - Material',NULL,NULL,NULL),
  ('SER057','Facilities Relocation / Removal - Other',NULL,NULL,NULL),
  ('SER058','Meter Test',NULL,NULL,NULL),
  ('SER059','Meter Test – Single Phase Self Contained',NULL,NULL,NULL),
  ('SER060','Meter Test - Three Phase Self Contained',NULL,NULL,NULL),
  ('SER061','Meter Test – Single Phase Instrument Rated',NULL,NULL,NULL),
  ('SER062','Meter Test - Three Phase Instrument Rated',NULL,NULL,NULL),
  ('SER063','Meter Test - Instrument Rated',NULL,NULL,NULL),
  ('SER064','PCB Inquiry',NULL,NULL,NULL),
  ('SER065','PCB Inquiry and Lab Testing - Labor',NULL,NULL,NULL),
  ('SER066','PCB Inquiry and Lab Testing -Transportation',NULL,NULL,NULL),
  ('SER067','PCB Inquiry and Lab Testing - Material',NULL,NULL,NULL),
  ('SER068','PCB Inquiry and Lab Testing -Other',NULL,NULL,NULL),
  ('SER069','PCB Inquiry - Additional Transformer',NULL,NULL,NULL),
  ('SER070','Service Call',NULL,NULL,NULL),
  ('SER071','Service Call After Hours',NULL,NULL,NULL),
  ('SER072','Tampering',NULL,NULL,NULL),
  ('SER073','Off-Site Meter Reading (OMR) Equipment Installation - Regular Hours',NULL,NULL,NULL),
  ('SER074','Off-Site Meter Reading (OMR) Equipment Installation - Outside Regular Hours - Non-Holiday',NULL,NULL,NULL),
  ('SER075','Off-Site Meter Reading (OMR) Equipment Installation - Outside Regular Hours - Holiday',NULL,NULL,NULL),
  ('SER076','Automated Meter Reading Equipment Installation - Single Phase Self Contained',NULL,NULL,NULL),
  ('SER077','Automated Meter Reading Equipment Installation - Three Phase Self Contained',NULL,NULL,NULL),
  ('SER078','Automated Meter Reading Equipment Installation - Single Phase Instrument Rated',NULL,NULL,NULL),
  ('SER079','Automated Meter Reading Equipment Installation - Three Phase Instrument Rated',NULL,NULL,NULL),
  ('SER080','Automated Meter Reading - Cycle Meter Read (Monthly)',NULL,NULL,NULL),
  ('SER081','Automated Meter Reading - Specific Date Meter Read (Monthly)',NULL,NULL,NULL),
  ('SER082','Advanced Metering Interval Load Data Equipment Installation -Labor',NULL,NULL,NULL),
  ('SER083','Advanced Metering Interval Load Data Equipment Installation - Transportation',NULL,NULL,NULL),
  ('SER084','Advanced Metering Interval Load Data Equipment Installation - Material',NULL,NULL,NULL),
  ('SER085','Advanced Metering Interval Load Data Equipment Installation - Other',NULL,NULL,NULL),
  ('SER086','Advanced Metering Interval Load Data Equipment Maintenance (Monthly)',NULL,NULL,NULL),
  ('SER087','Electrical Pulse Equipment Installation',NULL,NULL,NULL),
  ('SER088','Electrical Pulse Equipment Replacement Isolation Relay',NULL,NULL,NULL),
  ('SER089','Electrical Pulse Equipment Replacement Pulse Initiator',NULL,NULL,NULL),
  ('SER090','Electrical Pulse Equipment Replacement Isolation Relay & Pulse Initiator',NULL,NULL,NULL),
  ('SER091','Electrical Pulse Equipment Replacement Enclosure box',NULL,NULL,NULL),
  ('SER092','Electrical Pulse Equipment Maintenance (Monthly)',NULL,NULL,NULL),
  ('SER093','Dual Socket Meter Adapter',NULL,NULL,NULL),
  ('SER094','Power Factor Correction Equipment Installation - Labor',NULL,NULL,NULL),
  ('SER095','Power Factor Correction Equipment Installation - Material',NULL,NULL,NULL),
  ('SER096','Power Factor Correction Equipment Installation - Transportation',NULL,NULL,NULL),
  ('SER097','Power Factor Correction Equipment Installation - Other',NULL,NULL,NULL),
  ('SER098','Non-Standard Service Equipment Inspection/Testing',NULL,NULL,NULL),
  ('SER099','Retail Delivery Switchover',NULL,NULL,NULL),
  ('SER100','Retail Delivery Service Switchover Self Contained Base',NULL,NULL,NULL),
  ('SER101','Retail Delivery Service Switchover Self Contained Base Adder',NULL,NULL,NULL),
  ('SER102','Retail Delivery Service Switchover Instrument Rated Base',NULL,NULL,NULL),
  ('SER103','Retail Delivery Service Switchover Instrument Rated Base Adder',NULL,NULL,NULL),
  ('SER104','Retail Delivery Service Switchover Instrument Rated Facilities Recovery',NULL,NULL,NULL),
  ('SER105','Miscellaneous Discretionary',NULL,NULL,NULL),
  ('SER106','Miscellaneous Discretionary - Labor',NULL,NULL,NULL),
  ('SER107','Miscellaneous Discretionary - Material',NULL,NULL,NULL),
  ('SER108','Miscellaneous Discretionary - Transportation',NULL,NULL,NULL),
  ('SER109','Miscellaneous Discretionary - Other',NULL,NULL,NULL),
  ('SER110','Transmission Facilities Relocation Study',NULL,NULL,NULL),
  ('SER111','Transmission Facilities Relocation Study - Labor',NULL,NULL,NULL),
  ('SER112','Transmission Facilities Relocation Study - Material',NULL,NULL,NULL),
  ('SER113','Transmission Facilities Relocation Study - Transportation',NULL,NULL,NULL),
  ('SER114','Transmission Facilities Relocation Study - Other',NULL,NULL,NULL),
  ('SER115','Transmission Facilities Relocation',NULL,NULL,NULL),
  ('SER116','Transmission Facilities Relocation - Labor',NULL,NULL,NULL),
  ('SER117','Transmission Facilities Relocation - Material',NULL,NULL,NULL),
  ('SER118','Transmission Facilities Relocation - Transportation',NULL,NULL,NULL),
  ('SER119','Transmission Facilities Relocation - Other',NULL,NULL,NULL),
  ('SER120','Power Factor Correction Facilities Installation (Transmission)',NULL,NULL,NULL),
  ('SER121','Power Factor Correction Facilities Installation (Transmission) – Labor',NULL,NULL,NULL),
  ('SER122','Power Factor Correction Facilities Installation (Transmission) - Material',NULL,NULL,NULL),
  ('SER123','Power Factor Correction Facilities Installation (Transmission) - Transportation',NULL,NULL,NULL),
  ('SER124','Power Factor Correction Facilities Installation (Transmission) - Other',NULL,NULL,NULL),
  ('SER125','Miscellaneous Transmission Discretionary',NULL,NULL,NULL),
  ('SER126','Miscellaneous Transmission Discretionary - Labor',NULL,NULL,NULL),
  ('SER127','Miscellaneous Transmission Discretionary - Material',NULL,NULL,NULL),
  ('SER128','Miscellaneous Transmission Discretionary - Transportation',NULL,NULL,NULL),
  ('SER129','Miscellaneous Transmission Discretionary - Other',NULL,NULL,NULL),
  ('SER130','Broken Meter Seal',NULL,NULL,NULL),
  ('SER131','Service Conductor Temp Removal',NULL,NULL,NULL),
  ('SER132','Dispatch Order',NULL,NULL,NULL),
  ('SER133','Denial of Access to Meter',NULL,NULL,NULL),
  ('SER134','Underground Location',NULL,NULL,NULL),
  ('SER135','Meter Change',NULL,NULL,NULL),
  ('SER136','Extraordinary Maintenance Activity',NULL,NULL,NULL),
  ('SER137','Set Time Appointment',NULL,NULL,NULL),
  ('SER138','Non-TDSP Owned Meter Installation',NULL,NULL,NULL),
  ('SER139','Inadvertent Gain Charge',NULL,'2011-09-01','CC20011-786'),
  ('SER140','Meter Investigation Charge',NULL,'2011-09-01','CC20011-786'),
  ('SER141','Pole Attachment Service Charge','Unmetered Pole Attachment Service Charge','2019-09-12','CC2019-808'),
  ('TRN001','Transmission Service Charge','Transmission Charge',NULL,NULL),
  ('TRN002','Transmission Cost Recovery Factor','Firm Point-to-Point Transmission Service Charge for long-term/short-term firm point-to-point transmission service.',NULL,NULL)
ON DUPLICATE KEY UPDATE
  `description`           = VALUES(`description`),
  `market_description`    = VALUES(`market_description`),
  `implementation_date`   = VALUES(`implementation_date`),
  `change_control_number` = VALUES(`change_control_number`);
