-- Migration 044: reporting VIEWs used by the portfolio/collections dashboards.
--
-- These 9 views exist on the live/source DB right now but predate the
-- migration system entirely -- same class of undocumented drift as
-- confirmation_log (see migration 041's header comment). They were never
-- captured as CREATE VIEW statements anywhere in this repo.
--
-- Discovered 2026-09-23 while debugging a real 500 on GET /api/portfolio/summary
-- for a freshly-provisioned test tenant (rep_id=4, tenant_test_pilot_co):
-- portfolio_view didn't exist in the new tenant's DB. Root cause:
-- step_clone_schema() in api/scripts/provision_tenant.py deliberately clones
-- `SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'` only, skipping views --
-- so no view has ever been cloned into any provisioned tenant. All 9 are
-- captured here so they're tracked like every other schema object; the
-- clone-skip bug itself is fixed separately in step_clone_schema() (same
-- commit) so future provisioning includes them automatically.
--
-- DDL captured verbatim via `SHOW CREATE VIEW <name>` against the live
-- source DB (u972964962_orbic) on 2026-09-23, with only the
-- DEFINER=`root`@`localhost` clause stripped -- that's host/user-specific to
-- this machine's MySQL install and would silently fail (or silently bind to
-- the wrong account) if run as-is on the VPS. Omitting DEFINER makes MySQL
-- default it to whichever user actually runs this file, which is what every
-- other environment (VPS live, any future tenant clone) needs anyway.
-- CREATE OR REPLACE is used instead of a plain CREATE so this file can be
-- re-run safely if a view's definition ever needs to be corrected by a later
-- migration without dropping it first.
--
-- Not executed against any database -- for review and manual run only, same
-- pattern as every other migration in this project.

-- portfolio_view -- customer/contract rollup used by /api/portfolio/* (the
-- endpoint that surfaced this whole gap).
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `portfolio_view` AS select `contract_renewal`.`cust_id` AS `cust_id`,`contract_renewal`.`company_name` AS `company_name`,cast(`contract_renewal`.`premise_id` as char charset utf8mb4) AS `premise_id`,substring_index(substring_index(`contract_renewal`.`load_profile`,'_',2),'_',-1) AS `weather_zone`,case substring_index(substring_index(`contract_renewal`.`load_profile`,'_',2),'_',-1) when 'NCENT' then 'NORTH' when 'NORTH' then 'NORTH' when 'EAST' then 'NORTH' when 'SCENT' then 'SOUTH' when 'SOUTH' then 'SOUTH' when 'FWEST' then 'WEST' when 'WEST' then 'WEST' when 'COAST' then 'COAST' else 'UNKNOWN' end AS `zone`,`contract_renewal`.`load_profile` AS `load_profile`,case when `contract_renewal`.`contract_type` = 'Fix' then 'Fix' when `contract_renewal`.`contract_type` = 'LMP' then 'LMP' else 'MTM' end AS `contract_type`,`contract_renewal`.`contract_rate` AS `contract_rate`,str_to_date(`contract_renewal`.`contract_end_date`,'%m/%d/%Y') AS `contract_end_date`,`contract_renewal`.`contract_renewal_usage` AS `usage_kwh`,`contract_renewal`.`broker_code` AS `broker_code`,case when str_to_date(`contract_renewal`.`contract_end_date`,'%m/%d/%Y') >= curdate() then 'active' else 'expired' end AS `status` from `contract_renewal` where `contract_renewal`.`premise_id` is not null and `contract_renewal`.`load_profile` is not null and str_to_date(`contract_renewal`.`contract_end_date`,'%m/%d/%Y') > '2000-01-01';

-- v_account_balance -- per-account collections balance + latest payment + active plan.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_account_balance` AS select `ca`.`id` AS `collections_account_id`,`ca`.`esiid` AS `esiid`,`ca`.`account_number` AS `account_number`,`ca`.`customer_name` AS `customer_name`,`ca`.`track` AS `track`,`ca`.`stage` AS `stage`,`ca`.`usage_balance` AS `usage_balance`,`ca`.`etf_amount` AS `etf_amount`,`ca`.`etf_status` AS `etf_status`,`ca`.`etf_flag` AS `etf_flag`,`ca`.`total_due` AS `total_due`,`ca`.`amount_paid` AS `amount_paid`,`ca`.`last_payment_date` AS `last_payment_date`,`ca`.`last_payment_amount` AS `last_payment_amount`,`ca`.`days_overdue` AS `days_overdue`,`ca`.`delinquency_tier` AS `delinquency_tier`,`ca`.`is_payment_plan` AS `is_payment_plan`,`p`.`id` AS `last_payment_id`,`p`.`amount` AS `last_payment_posted_amount`,`p`.`method` AS `last_payment_method`,`p`.`payment_date` AS `last_payment_sheet_date`,`p`.`status` AS `last_payment_status`,`p`.`source` AS `last_payment_source`,`pp`.`id` AS `active_plan_id`,`pp`.`num_installments` AS `num_installments`,`pp`.`installment_amount` AS `installment_amount`,`pp`.`frequency` AS `frequency`,`pp`.`next_due_date` AS `next_due_date` from ((`collections_accounts` `ca` left join `payments` `p` on(`p`.`collections_account_id` = `ca`.`id` and `p`.`id` = (select `payments`.`id` from `payments` where `payments`.`collections_account_id` = `ca`.`id` and `payments`.`status` = 'POSTED' order by `payments`.`received_date` desc limit 1))) left join (select `pp2`.`id` AS `id`,`pp2`.`account_id` AS `account_id`,`pp2`.`num_installments` AS `num_installments`,`pp2`.`installment_amount` AS `installment_amount`,`pp2`.`frequency` AS `frequency`,min(`ppi`.`due_date`) AS `next_due_date` from (`collections_payment_plans` `pp2` join `payment_plan_installments` `ppi` on(`ppi`.`payment_plan_id` = `pp2`.`id`)) where `pp2`.`status` = 'ACTIVE' and `ppi`.`status` = 'SCHEDULED' group by `pp2`.`id`,`pp2`.`account_id`,`pp2`.`num_installments`,`pp2`.`installment_amount`,`pp2`.`frequency`) `pp` on(`pp`.`account_id` = `ca`.`id`));

-- v_aging_buckets -- AR aging (1-30/31-60/61-90/91-120/120+) grouped by track.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_aging_buckets` AS select `collections_accounts`.`track` AS `track`,sum(case when `collections_accounts`.`days_overdue` between 1 and 30 then `collections_accounts`.`total_due` else 0 end) AS `bucket_1_30`,sum(case when `collections_accounts`.`days_overdue` between 31 and 60 then `collections_accounts`.`total_due` else 0 end) AS `bucket_31_60`,sum(case when `collections_accounts`.`days_overdue` between 61 and 90 then `collections_accounts`.`total_due` else 0 end) AS `bucket_61_90`,sum(case when `collections_accounts`.`days_overdue` between 91 and 120 then `collections_accounts`.`total_due` else 0 end) AS `bucket_91_120`,sum(case when `collections_accounts`.`days_overdue` > 120 then `collections_accounts`.`total_due` else 0 end) AS `bucket_120_plus`,sum(`collections_accounts`.`total_due`) AS `total_due`,count(0) AS `account_count` from `collections_accounts` where `collections_accounts`.`is_paid` = 0 and `collections_accounts`.`stage` not in ('RESOLVED','WRITTEN_OFF') group by `collections_accounts`.`track`;

-- v_approval_queue_pending -- pending, non-expired collections approval-queue items with account context.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_approval_queue_pending` AS select `q`.`id` AS `id`,`q`.`account_id` AS `account_id`,`q`.`action_type` AS `action_type`,`q`.`case_summary` AS `case_summary`,`q`.`case_data` AS `case_data`,`q`.`recommended_action` AS `recommended_action`,`q`.`risk_level` AS `risk_level`,`q`.`puc_compliant` AS `puc_compliant`,`q`.`puc_notes` AS `puc_notes`,`q`.`status` AS `status`,`q`.`reviewed_by` AS `reviewed_by`,`q`.`reviewed_at` AS `reviewed_at`,`q`.`reviewer_notes` AS `reviewer_notes`,`q`.`expires_at` AS `expires_at`,`q`.`created_by` AS `created_by`,`q`.`created_at` AS `created_at`,`a`.`customer_name` AS `customer_name`,`a`.`account_number` AS `account_number`,`a`.`esiid` AS `esiid`,`a`.`track` AS `track`,`a`.`stage` AS `stage`,`a`.`total_due` AS `total_due`,`a`.`days_overdue` AS `days_overdue`,`a`.`delinquency_tier` AS `delinquency_tier`,`a`.`broker_name` AS `broker_name`,`a`.`is_dnp_active` AS `is_dnp_active`,`a`.`dnp_eligible_after` AS `dnp_eligible_after` from (`collections_approval_queue` `q` join `collections_accounts` `a` on(`q`.`account_id` = `a`.`id`)) where `q`.`status` = 'PENDING' and `q`.`expires_at` > current_timestamp() order by `q`.`risk_level` desc,`q`.`created_at`;

-- v_arr_exposure -- at-risk revenue grouped by track/stage/delinquency tier.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_arr_exposure` AS select `collections_accounts`.`track` AS `track`,`collections_accounts`.`stage` AS `stage`,`collections_accounts`.`delinquency_tier` AS `delinquency_tier`,count(0) AS `account_count`,sum(`collections_accounts`.`usage_balance`) AS `total_usage_due`,sum(`collections_accounts`.`etf_amount`) AS `total_etf_due`,sum(`collections_accounts`.`total_due`) AS `total_at_risk`,sum(case when `collections_accounts`.`etf_flag` = 1 then 1 else 0 end) AS `etf_open_count`,avg(`collections_accounts`.`days_overdue`) AS `avg_days_overdue`,max(`collections_accounts`.`days_overdue`) AS `max_days_overdue` from `collections_accounts` where `collections_accounts`.`is_paid` = 0 and `collections_accounts`.`stage` not in ('RESOLVED','WRITTEN_OFF') group by `collections_accounts`.`track`,`collections_accounts`.`stage`,`collections_accounts`.`delinquency_tier`;

-- v_bounced_payments -- bounced payments joined with their collections account.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_bounced_payments` AS select `p`.`id` AS `id`,`p`.`esiid` AS `esiid`,`p`.`account_number` AS `account_number`,`p`.`customer_name` AS `customer_name`,`p`.`collections_account_id` AS `collections_account_id`,`p`.`payment_date` AS `payment_date`,`p`.`received_date` AS `received_date`,`p`.`amount` AS `amount`,`p`.`method` AS `method`,`p`.`reference_number` AS `reference_number`,`p`.`applied_to` AS `applied_to`,`p`.`applied_to_usage` AS `applied_to_usage`,`p`.`applied_to_etf` AS `applied_to_etf`,`p`.`balance_before` AS `balance_before`,`p`.`balance_after` AS `balance_after`,`p`.`usage_balance_before` AS `usage_balance_before`,`p`.`usage_balance_after` AS `usage_balance_after`,`p`.`etf_balance_before` AS `etf_balance_before`,`p`.`etf_balance_after` AS `etf_balance_after`,`p`.`triggered_etf_flag` AS `triggered_etf_flag`,`p`.`source` AS `source`,`p`.`import_id` AS `import_id`,`p`.`entered_by` AS `entered_by`,`p`.`is_bounced` AS `is_bounced`,`p`.`bounced_at` AS `bounced_at`,`p`.`bounce_reason` AS `bounce_reason`,`p`.`bounce_notified_at` AS `bounce_notified_at`,`p`.`reversal_of_payment_id` AS `reversal_of_payment_id`,`p`.`status` AS `status`,`p`.`notes` AS `notes`,`p`.`created_at` AS `created_at`,`p`.`updated_at` AS `updated_at`,`ca`.`track` AS `ca_track`,`ca`.`stage` AS `ca_stage`,`ca`.`broker_name` AS `ca_broker_name`,`ca`.`assigned_to` AS `ca_assigned_to`,`ca`.`delinquency_tier` AS `ca_delinquency_tier` from (`payments` `p` join `collections_accounts` `ca` on(`p`.`collections_account_id` = `ca`.`id`)) where `p`.`is_bounced` = 1 and `p`.`status` = 'BOUNCED' order by `p`.`bounced_at` desc;

-- v_etf_open -- open (non-waived, non-collected) early-termination fees.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_etf_open` AS select `a`.`id` AS `id`,`a`.`customer_name` AS `customer_name`,`a`.`account_number` AS `account_number`,`a`.`track` AS `track`,`a`.`stage` AS `stage`,`a`.`usage_balance` AS `usage_balance`,`e`.`original_amount` AS `etf_original`,`e`.`current_amount` AS `etf_current`,`e`.`collected_amount` AS `etf_collected`,`e`.`status` AS `etf_status`,`a`.`days_overdue` AS `days_overdue`,`a`.`broker_name` AS `broker_name` from (`collections_accounts` `a` join `collections_etf` `e` on(`a`.`id` = `e`.`account_id`)) where `a`.`etf_flag` = 1 and `e`.`status` not in ('WAIVED','COLLECTED') order by `e`.`current_amount` desc;

-- v_missed_installments -- missed/still-scheduled-but-overdue payment plan installments.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_missed_installments` AS select `ppi`.`id` AS `id`,`ppi`.`payment_plan_id` AS `payment_plan_id`,`ppi`.`collections_account_id` AS `collections_account_id`,`ppi`.`installment_number` AS `installment_number`,`ppi`.`due_date` AS `due_date`,`ppi`.`amount_due` AS `amount_due`,`ppi`.`payment_id` AS `payment_id`,`ppi`.`paid_date` AS `paid_date`,`ppi`.`paid_amount` AS `paid_amount`,`ppi`.`status` AS `status`,`ppi`.`missed_notified_at` AS `missed_notified_at`,`ppi`.`grace_period_ends` AS `grace_period_ends`,`ppi`.`notes` AS `notes`,`ppi`.`created_at` AS `created_at`,`ppi`.`updated_at` AS `updated_at`,`ca`.`customer_name` AS `customer_name`,`ca`.`esiid` AS `esiid`,`ca`.`track` AS `track`,`ca`.`stage` AS `stage`,`ca`.`broker_name` AS `broker_name`,`ca`.`assigned_to` AS `assigned_to`,`pp`.`total_amount` AS `plan_total`,`pp`.`num_installments` AS `num_installments`,`pp`.`status` AS `plan_status` from ((`payment_plan_installments` `ppi` join `collections_accounts` `ca` on(`ppi`.`collections_account_id` = `ca`.`id`)) join `collections_payment_plans` `pp` on(`ppi`.`payment_plan_id` = `pp`.`id`)) where `ppi`.`status` in ('MISSED','SCHEDULED') and `ppi`.`due_date` < curdate() order by `ppi`.`due_date`;

-- v_payments_today -- today's payments grouped by source/method, with bounce count.
CREATE OR REPLACE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v_payments_today` AS select `payments`.`source` AS `source`,`payments`.`method` AS `method`,count(0) AS `payment_count`,sum(`payments`.`amount`) AS `total_amount`,sum(`payments`.`applied_to_usage`) AS `applied_to_usage`,sum(`payments`.`applied_to_etf`) AS `applied_to_etf`,sum(`payments`.`triggered_etf_flag`) AS `etf_flags_triggered`,sum(case when `payments`.`is_bounced` = 1 then 1 else 0 end) AS `bounced_count` from `payments` where cast(`payments`.`received_date` as date) = curdate() group by `payments`.`source`,`payments`.`method`;
